### ISSUE TITLE
Invalid connection string attribute

### ISSUE THREAD

**Issue by IlyaMalyutin** [mkleehammer/pyodbc#507] opened 2019-01-15 09:16 UTC
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit: 

- Python: Python 3.5.2
- pyodbc: 4.0.25
- OS: Ubuntu:16.04
- DB: Microsoft SQL Server 2016 (SP1-CU8) (KB4077064) - 13.0.4474.0 (X64) 
- driver: ODBC Driver 13 for SQL Server

### Issue
DB admin asked me about failed login message in db, like "Logon,Unknown,Login failed for user 'user'. Reason: Password did not match that for the login provided. [CLIENT: 127.0.0.1]".
But there are no any exceptions in the service which works with this db. I turned on ODBC trace mode and discovered the situation like this:
```[ODBC][1464][1547213406.523135][SQLDriverConnectW.c][290]
                Entry:
                        Connection = 0x2f8e930
                        Window Hdl = (nil)
                        Str In = [DRIVER={ODBC Driver 13 for SQL Server};SERVER=127.0.0.1;PORT=1433;DATABASE=dbname;UID=user;PWD=pwd][length = 108 (SQL_NTS)]
                        Str Out = (nil)
                        Str Out Max = 0
                        Str Out Ptr = (nil)
                        Completion = 0
                UNICODE Using encoding ASCII 'ISO8859-1' and UNICODE 'UCS-2LE'

[ODBC][1464][1547213406.545475][SQLDriverConnectW.c][699]
                Exit:[SQL_ERROR]
[ODBC][1464][1547213406.545520][SQLDriverConnect.c][726]
                Entry:
                        Connection = 0x2f8e930
                        Window Hdl = (nil)
                        Str In = [DRIVER={ODBC Driver 13 for SQL Server};SERVER=127.0.0.1;PORT=1433;DATABASE=dbname;UID=user;PWD=*********][length = 107 (SQL_NTS)]
                        Str Out = 0x7ffda0246350
                        Str Out Max = 2048
                        Str Out Ptr = (nil)
                        Completion = 0
                UNICODE Using encoding ASCII 'ISO8859-1' and UNICODE 'UCS-2LE'
                DIAG [01000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Changed database context to 'dbname'.
                DIAG [01000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Changed language setting to us_english.
                DIAG [01S00] [Microsoft][ODBC Driver 13 for SQL Server]Invalid connection string attribute
```
ODBC repeats the action several times and after success continues to work. The connection string itself is valid and the problem is hardly reproduced, once in several thousand connections.

After rolled back on pyodbc==4.0.24 problem was solved.

**Comment by v-chojas** [comment] 2019-01-15 15:37
What version of unixODBC are you using? Check using `odbcinst -j`.

**Comment by v-chojas** [comment] 2019-01-16 15:49
There are a lot of bugs that have been fixed in the DM since then, the latest is 2.3.7. You can see them at 
http://www.unixodbc.org/ . Please try the latest unixODBC and see if the problem still reproduces.

**Comment by gordthompson** [comment] 2019-01-16 20:18
Microsoft's ODBC Drivers for SQL Server do not support a `PORT=` attribute. Instead, the port number, if any, needs to be appended to the server name/IP with a comma. That is ...

... not this ...

`SERVER=192.168.0.188;PORT=45678`

... but this ...

`SERVER=192.168.0.188,45678`

That might very well be the source of the "Invalid connection string attribute" warning.

**Comment by keitherskine** [comment] 2021-05-29 17:25
Closed due to inactivity. Feel free to re-open with current information if necessary.

**Closed by keitherskine** 2021-05-29 17:25 UTC
Labels: Environment or Driver Issue, Waiting for Info
