### ISSUE TITLE
pyodbc - turning transactions off

### ISSUE THREAD

**Issue by jastis1** [mkleehammer/pyodbc#222] opened 2017-04-04 11:11 UTC
To set the context, I am connecting to SQl Server using pyodbc default setting ( autoCommit=False) and then changing the status to True. (cnxn.autoCommit=True). I am multi threading in my code, where I open connection(as stated above) in the main function and start the threads and in each of those threads I open the connection using the same settings, do multiple Insert statements( with medium complex queries) and then close the connection after each thread is done and finally close the connection in the main function. The issue that I am seeing is that, even after setting the autoCommit to True, I see open transactions( one  for each thread). I am not using any cnxn.commit() 's in my code. The performance is taking a big hit with those transactions. Can you please help me with any work around for this? Also, please let me know if there is any flaw in my approach of setting the status of connection. Thanks

**Comment by gordthompson** [comment] 2017-04-05 10:58
Does it make any difference if you open the connections with `autocommit=True` as an argument to the `.connect` call, rather than opening the connection with autocommit off (the default) and then setting `cnxn.autocommit = True`?

**Comment by jastis1** [comment] 2017-04-05 18:09
No, it doesn't make any difference.

**Comment by keitherskine** [comment] 2017-04-05 18:31
Just to be clear @jastis1 , how many database connections do you have open at any one time, and how many cursors do you have open on each of those connections at any one time (maximum values) ?

Also, do those INSERT statements write to the same tables?  That is, would they probably block each other?

**Comment by mkleehammer** [comment] 2017-04-05 19:13
The code looks like it is doing the right thing - setting the connection's autocommit attribute correctly.  If so, it means we are going to have to look at Python, the driver, or the server.

I wonder if the transactions aren't normal.  The autocommit mode docs for SQL Server simply say the batch will be committed immediately, but it doesn't say transactions won't show up at all.  Can this be reproduced using SQL Management Studio?  (Also, what you are looking at to see the txns so I can do the same?)

It's possible poor performance is from something else.  A couple of things come to mind.  First, what version are you using?  I'm assuming 4.0.16, but if not it might be important.

One thing that *shouldn't* be a problem with SQL Server is insert buffer size - it should be writing each varchar, nvarchar, and binary in one chunk instead of using SQLPutData.  However, make sure you are using the latest for this.

Are you writing a lot of varchar or nvarchar columns?  These require encoding the text into the right format.  What version of Python are you using?  This could matter a lot since Python 3 uses Unicode for all text.  

If you are using Python 2 and know your data is ASCII or latin1 only and matches the SQL Server encoding, you can cheat sometimes.  See the [Unicode](https://github.com/mkleehammer/pyodbc/wiki/Unicode) Wiki page.  In particular, you can set the `str` encoding to "raw" and the bytes will be passed as-is. You are responsible for ensuring that the bytes you are passing match the SQL Server encoding because it will simply store it.

If you are using Python 3 and are only writing ASCII or latin1, you can set the encoding to latin1.

Anyway, look at these and update us with this info and what keitherskine asked about:

* Python version
* pyodbc version
* SQL Server version
* SQL Server ODBC driver version

Here's an easy way to get these:

``` python
import sys, platform, os
import pyodbc

cnxn = pyodbc.connect(...)
cursor = cnxn.cursor()

print('python:  %s' % sys.version)
print('pyodbc:  %s %s' % (pyodbc.version, os.path.abspath(pyodbc.__file__)))
print('odbc:    %s' % cnxn.getinfo(pyodbc.SQL_ODBC_VER))
print('driver:  %s %s' % (cnxn.getinfo(pyodbc.SQL_DRIVER_NAME), cnxn.getinfo(pyodbc.SQL_DRIVER_VER)))
print('         supports ODBC version %s' % cnxn.getinfo(pyodbc.SQL_DRIVER_ODBC_VER))
print('os:      %s' % platform.system())
print('unicode: Py_Unicode=%s SQLWCHAR=%s' % (pyodbc.UNICODE_SIZE, pyodbc.SQLWCHAR_SIZE))

if platform.system() == 'Windows':
    print('Windows: %s' % ' '.join([s for s in platform.win32_ver() if s]))

row = cursor.execute("select convert(varchar(100), serverproperty('ProductVersion'))").fetchone()
print('SQL Server: %s' % row[0])

cursor = cnxn.cursor()
for typename in ['VARCHAR', 'WVARCHAR', 'BINARY']:
    t = getattr(pyodbc, 'SQL_' + typename)
    cursor.getTypeInfo(t)
    row = cursor.fetchone()
    print('Max %s = %s' % (typename, row and row[2] or '(not supported)'))
```

**Comment by jastis1** [comment] 2017-04-06 12:19
My code is having 5 open connections at a time , as I have 5 threads in my code that insert data to the same tables. But, I handled that
using the following code in python
   ` while True:
        try:
            cursor.execute(SQLPreparedStatement) 
        except Exception, err:
            continue
        break`
I ran the code given by @mkleehammer  and here is the output:

`python:  2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
pyodbc:  3.0.10 /apps/conda3/envs/py27/lib/python2.7/site-packages/pyodbc.so
odbc:    03.52
driver:  libtdsodbc.so 00.95.0079
         supports ODBC version 03.50
os:      Linux
unicode: Py_Unicode=4 SQLWCHAR=4
SQL Server: 12.0.5000.0
Max VARCHAR = 8000
Max WVARCHAR = 4000
Max BINARY = 8000
`

**Comment by colin-streicher** [comment] 2017-05-17 14:42
5 threads all inserting to the same table is nearly always going to have bad performance unless it is a very small table with no indexes. The open transactions you see are likely a result of locking the table to do the update, setting the autocommit setting just means that the commit is implicit, it still has to do the commit on the table to write out the data. In this case, a commit means locking the table and blocking all other writes. 

You are seeing transactions open because there are 5 threads competeing for resources. 

I have no idea what sort of data you are dealing with, but I question if 5 threads are worth it. If you really need it, I would actually suggest inserting in batches with autocommit turned off. This way you can send a few hundred/thousand rows in, commit, and do the same thing again. If you do it this way, you might see better performance, just make sure to keep track of whats been commited.

**Comment by keitherskine** [comment] 2021-05-29 17:36
Closed due to inactivity. Feel free to re-open with current information if necessary.

**Closed by keitherskine** 2021-05-29 17:36 UTC
