### ISSUE TITLE
How to read SQL print messages?

### ISSUE THREAD

**Issue by sivaprakashmp** [mkleehammer/pyodbc#583] opened 2019-07-11 09:02 UTC
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment
Linux 3.10.0-957.10.1.el7.x86_64

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.3
- pyodbc: 4.0.26
- OS: Linux
- DB: MSSQL
- driver: 

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

I have series of print statements within my TSQL statements. How to read the out messages from these print statements in python? I can't find a solution so far. Much appreciate any help here. Thanks.!

I tried cursor.messages & connection.messages. But the print messages are not present here.

SP

**Comment by mkleehammer** [comment] 2019-07-11 13:29
We have some SQL Server experts here that will hopefully chime in.  We should add this to the SQL Server wiki page.  I've seen this question before.

**Comment by v-chojas** [comment] 2019-07-11 14:46
@mkleehammer yes, it was a feature request we were discussing here: https://github.com/mkleehammer/pyodbc/issues/495

@sivaprakashmp those messages will be returned as diagnostic records when the SQLExecute()/SQLExecDirect() ODBC API  returns "success with info". Currently there is no way to retrieve these from pyODBC because it does not save them after execution; it only distinguishes between success/error.

**Comment by sivaprakashmp** [comment] 2019-07-12 09:45
> @mkleehammer yes, it was a feature request we were discussing here: #495
> 
> @sivaprakashmp those messages will be returned as diagnostic records when the SQLExecute()/SQLExecDirect() ODBC API returns "success with info". Currently there is no way to retrieve these from pyODBC because it does not save them after execution; it only distinguishes between success/error.

@v-chojas exactly, thats the same issue I am taking about. I have posted my comments there and would be very happy to test this if needed. I think this issue can be merged with #495

**Comment by gordthompson** [comment] 2021-05-29 16:59
Duplicate of #495

**Closed by gordthompson** 2021-05-29 16:59 UTC
