### ISSUE TITLE
Silent failures when using fast_executemany

### ISSUE THREAD

**Issue by mfow** [mkleehammer/pyodbc#665] opened 2019-12-27 02:52 UTC
### Environment

- Python: Python 3.7.5
- pyodbc: pyodbc==4.0.28
- OS: Windows 10 18362.535
- DB: Azure SQL Server
- Driver: ODBC Driver 17 for SQL Server 2017.174.02.01 10/2/2019

### Issue

I have created a SPROC that does some basic parameter validation, and runs an INSERT statement.

**Expected behavior:**

I call the sproc using executemany, with two rows of data. The first row of data is valid, the 2nd row conflicts with an existing row in the database (or otherwise causes the call to fail).

```
cursor: pyodbc.Cursor = connection.cursor()
cursor.fast_executemany = False
cursor.executemany('EXEC my_sproc_name @foo = ?, @bar = ?', my_data)
cursor.commit()

```
This throws an exception, as expected:

> "('23000', \"[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert duplicate key row in object 'dbo.candlesticks' with unique index 'candlesticks_instrument_id_timestamp_uindex'. The duplicate key value is (26, 2010-02-03 19:39:58.0000000). (2601) (SQLExecute); [23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated. (3621)\")

I run the same code again, but instead set `fast_executemany = True`. I expect that the same exception be thrown.

**Observed behavior:**

I observe the exception in the case that:
- when I set `fast_executemany = False`
- AND/OR, when the first row in my_data causes a failure

but not when I set fast_executemany = True, while the 1st row in my_data is valid.

To make things worse: In the case that fast_executemany = True, the first row of my_data is valid, and the 2nd row is not, not only does the call succeed, but the change from the first SPROC call is committed to the database while the 2nd change is not.

**Comment by gordthompson** [comment] 2019-12-27 14:05
I am unable to reproduce your issue.

Test environment:

```sql
CREATE TABLE [dbo].[tbl_pyodbc_665](
    [id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
    [id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO tbl_pyodbc_665 (id) VALUES (2);
GO

CREATE PROCEDURE [dbo].[pyodbc_665] 
    @id int = 0
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO tbl_pyodbc_665 (id) VALUES (@id);
END
GO
```

Test code:

```python
import sys

import pyodbc

print(f"Python version {sys.version}")
# Python version 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)]

print(f"pyodbc version {pyodbc.version}")
# pyodbc version 4.0.28

connection_string = get_conn_str()
print(connection_string)
# DRIVER=ODBC Driver 17 for SQL Server;SERVER=localhost,49242;DATABASE=myDb;Trusted_Connection=Yes;UseFMTONLY=Yes;

cnxn = pyodbc.connect(connection_string, autocommit=False)

print(f'driver: {cnxn.getinfo(pyodbc.SQL_DRIVER_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}')
# driver: msodbcsql17.dll, version 17.04.0001

print(f'server: {cnxn.getinfo(pyodbc.SQL_DBMS_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DBMS_VER)}')
# server: Microsoft SQL Server, version: 14.00.2027

crsr = cnxn.cursor()

crsr.execute("DELETE FROM tbl_pyodbc_665 WHERE id = 1")
cnxn.commit()
sql = "EXEC pyodbc_665 @id=?"
data = [(1,), (2,)]
crsr.fast_executemany = True
crsr.executemany(sql, data)
cnxn.commit()
```

I consistently get ...

```
Traceback (most recent call last):
  File "C:/Users/Gord/PycharmProjects/py3pyodbc_demo/main.py", line 66, in <module>
    crsr.executemany(sql, data)
pyodbc.IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of PRIMARY KEY constraint 'PK__tbl_pyod__3213E83F45E49883'. Cannot insert duplicate key in object 'dbo.tbl_pyodbc_665'. The duplicate key value is (2). (2627) (SQLExecute); [23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated. (3621)")
```

... and the first row (id = 1) is not committed.

**Comment by cheenamalhotra** [comment] 2019-12-27 17:42
Hi @gordthompson 

Would you also consider testing against Azure SQL Server, if the problem is respective to Azure DB as user reports against it? Just to verify the issue exists.

_(Sql Client Drivers team will be available post next week for further investigations)_

**Comment by gordthompson** [comment] 2019-12-27 23:58
Hi @cheenamalhotra - I'd be happy to test against Azure SQL but I don't have access to an instance. :(

**Comment by cheenamalhotra** [comment] 2019-12-28 00:47
I tested against Azure SQL DB and get the same error:

`pyodbc.IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of PRIMARY KEY constraint 'PK__tbl_pyod__3213E83FDD390B43'. Cannot insert duplicate key in object 'dbo.tbl_pyodbc_665'. The duplicate key value is (2). (2627) (SQLExecute); [23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated. (3621)")`

@mfow 

Please confirm if the repro by @gordthompson is same as your use-case or you have a different usecase?

**Comment by mfow** [comment] 2020-01-04 22:55
@cheenamalhotra, the repro from @gordthompson looks similar to my use case and I'm surprised it didn't repro.

This is my use case, and I'm able to repro it in a new Azure SQL instance

`create table instruments
(
    instrument_id      int identity
        constraint instruments_pk
            primary key nonclustered,
    symbol             nvarchar(10)    not null,
    display_name       nvarchar(50)    not null,
    display_precision  int,
    pip_location       int,
    instrument_type    nvarchar(10),
    margin_rate        decimal(38, 10) not null,
    max_order_units    decimal(38, 10) not null,
    max_position_size  decimal(38, 10) not null,
    max_trail_distance decimal(38, 10) not null,
    min_trail_distance decimal(38, 10) not null,
    min_trade_size     decimal(38, 10) not null
)
go

create unique index instruments_symbol_uindex
    on instruments (symbol)
go

create unique index instruments_display_name_uindex
    on instruments (display_name)
go


INSERT INTO dbo.instruments (symbol, display_name, display_precision, pip_location, instrument_type, margin_rate, max_order_units, max_position_size, max_trail_distance, min_trail_distance, min_trade_size) VALUES ('EUR_USD', 'EUR/USD', 5, -4, 'CURRENCY', 0.0200000000, 100000000.0000000000, 0.0000000000, 1.0000000000, 0.0005000000, 1.0000000000);
go


create table candlesticks
(
    candlestick_id bigint identity
        constraint candlesticks_pk
            primary key nonclustered,
    volume         bigint          not null,
    bid_open       decimal(38, 10) not null,
    bid_high       decimal(38, 10) not null,
    bid_low        decimal(38, 10) not null,
    bid_close      decimal(38, 10) not null,
    ask_open       decimal(38, 10) not null,
    ask_high       decimal(38, 10) not null,
    ask_low        decimal(38, 10) not null,
    ask_close      decimal(38, 10) not null,
    timestamp      datetime2       not null,
    instrument_id  int             not null
        constraint candlesticks_instruments_instrument_id_fk
            references instruments
)
go

create unique index candlesticks_instrument_id_timestamp_uindex
    on candlesticks (instrument_id, timestamp)
go

create unique index candlesticks_timestamp_instrument_id_uindex
    on candlesticks (timestamp, instrument_id)
go


CREATE PROCEDURE insert_candlestick(@symbol AS nvarchar(10), @timestamp AS datetime2, @volume bigint,
                                   @bid_open decimal(38, 10), @bid_high decimal(38, 10), @bid_low decimal(38, 10),
                                   @bid_close decimal(38, 10),
                                   @ask_open decimal(38, 10), @ask_high decimal(38, 10), @ask_low decimal(38, 10),
                                   @ask_close decimal(38, 10)) AS
BEGIN
    SET NOCOUNT ON
    SET ANSI_NULLS OFF

    DECLARE @symbol_id AS INT

    IF (@timestamp > SYSUTCDATETIME())
        BEGIN
            RAISERROR ('Bad timestamp. Timestamp must be earlier than the current time.', 0, 1)
        END

    IF (@bid_open > @bid_high) OR (@bid_close > @bid_high) OR (@bid_low > @bid_high)
        BEGIN
            RAISERROR ('Bad bid', 0, 2)
        END

    IF (@bid_open < @bid_low) OR (@bid_close < @bid_low) OR (@bid_high < @bid_low)
        BEGIN
            RAISERROR ('Bad bid', 0, 3)
        END

    IF (@ask_open > @ask_high) OR (@ask_close > @ask_high) OR (@ask_low > @ask_high)
        BEGIN
            RAISERROR ('Bad ask', 0, 4)
        END

    IF (@ask_open < @ask_low) OR (@ask_close < @ask_low) OR (@ask_high < @ask_low)
        BEGIN
            RAISERROR ('Bad ask', 0, 5)
        END

    IF (@ask_open < @bid_open) OR (@ask_close < @bid_close) OR (@ask_high < @bid_high) OR (@ask_low < @bid_low)
        BEGIN
            RAISERROR ('Bad bid/ask spread', 0, 6)
        END

    SELECT @symbol_id = instrument_id FROM instruments WHERE instruments.symbol = @symbol

    IF (ISNULL(@symbol_id, 0) = 0)
        BEGIN
            RAISERROR ('Bad symbol', 0, 6)
        END

    INSERT candlesticks (instrument_id, timestamp, volume, bid_open, bid_high, bid_low, bid_close,
                         ask_open, ask_high, ask_low, ask_close)
    VALUES (@symbol_id, @timestamp, @volume,
            @bid_open, @bid_high, @bid_low, @bid_close,
            @ask_open, @ask_high, @ask_low, @ask_close)

    SELECT new_identity = SCOPE_IDENTITY()
END;
go
`

`import sys
from datetime import datetime
from decimal import Decimal
import pyodbc


def get_conn_str():
    connection_args = {
        'DRIVER': '{ODBC Driver 17 for SQL Server}',
        'DATABASE': 'REMOVED',
        'SERVER': 'REMOVED.database.windows.net',
        'UID': 'REMOVED',
        'PWD': "REMOVED"
    }

    return ';'.join(map(lambda key: '{}={}'.format(key, connection_args[key]), connection_args))


def main():
    print(f"Python version {sys.version}")
    # Python version 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]

    print(f"pyodbc version {pyodbc.version}")
    # pyodbc version 4.0.28

    connection_string = get_conn_str()
    print(connection_string)
    # DRIVER={ODBC Driver 17 for SQL Server};DATABASE=REMOVED;SERVER=REMOVED.database.windows.net;UID=REMOVED;PWD=REMOVED

    cnxn = pyodbc.connect(connection_string, autocommit=False)

    print(f'driver: {cnxn.getinfo(pyodbc.SQL_DRIVER_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}')
    # driver: msodbcsql17.dll, version: 17.04.0002

    print(f'server: {cnxn.getinfo(pyodbc.SQL_DBMS_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DBMS_VER)}')
    # server: Microsoft SQL Server, version: 12.00.2000

    crsr = cnxn.cursor()

    def print_candlesticks():
        print('listing candlesticks')
        crsr.execute('SELECT timestamp FROM candlesticks')

        for x in crsr.fetchall():
            print(x)
        print('----')

    def delete_all():
        crsr.execute("DELETE FROM candlesticks WHERE 1=1")
        cnxn.commit()

    sql = 'EXEC insert_candlestick @symbol=?, @timestamp=?, @volume=?, @bid_open=?, @bid_high=?, @bid_low=?, @bid_close=?, @ask_open=?, @ask_high=?, @ask_low=?, @ask_close=?'

    row1 = ('EUR_USD', datetime(year=2020, month=1, day=1), 1234,
            Decimal('1.12'), Decimal('1.12'), Decimal('1.12'), Decimal('1.12'),
            Decimal('1.12'), Decimal('1.12'), Decimal('1.12'), Decimal('1.12'))

    row2 = ('EUR_USD', datetime(year=2010, month=1, day=3, hour=17, minute=53, second=25), 4321,
            Decimal('1.12'), Decimal('1.12'), Decimal('1.12'), Decimal('1.12'),
            Decimal('1.12'), Decimal('1.12'), Decimal('1.12'), Decimal('1.12'))

    def run_test():
        # reset the database
        delete_all()
        print('with no data')
        print_candlesticks()

        # insert row2 only
        crsr.executemany(sql, [row2])
        cnxn.commit()

        print('only row 2')
        print_candlesticks()

        # insert both rows, this should fail.

        crsr.executemany(sql, [row1, row2])
        cnxn.commit()

        print('after both inserts')
        print_candlesticks()

    crsr.fast_executemany = True
    print('running test with fast_executemany=True')
    run_test() # doesn't fail

    crsr.fast_executemany = False
    print('running test with fast_executemany=False')
    run_test()  # fails


if __name__ == '__main__':
    main()

`

`"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe" C:/repos/fx2/src/py/apps/db_endpoint/repro_db_issue.py
Python version 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
pyodbc version 4.0.28
DRIVER={ODBC Driver 17 for SQL Server};DATABASE=[REMOVED]
driver: msodbcsql17.dll, version: 17.04.0002
server: Microsoft SQL Server, version: 12.00.2000
running test with fast_executemany=True
with no data
listing candlesticks
----
only row 2
listing candlesticks
(datetime.datetime(2010, 1, 3, 17, 53, 25), )
----
after both inserts
listing candlesticks
(datetime.datetime(2010, 1, 3, 17, 53, 25), )
(datetime.datetime(2020, 1, 1, 0, 0), )
----
running test with fast_executemany=False
with no data
listing candlesticks
----
only row 2
listing candlesticks
(datetime.datetime(2010, 1, 3, 17, 53, 25), )
----
Traceback (most recent call last):
  File "C:/repos/fx2/src/py/apps/db_endpoint/repro_db_issue.py", line 89, in <module>
    main()
  File "C:/repos/fx2/src/py/apps/db_endpoint/repro_db_issue.py", line 85, in main
    run_test()
  File "C:/repos/fx2/src/py/apps/db_endpoint/repro_db_issue.py", line 73, in run_test
    crsr.executemany(sql, [row1, row2])
pyodbc.IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert duplicate key row in object 'dbo.candlesticks' with unique index 'candlesticks_instrument_id_timestamp_uindex'. The duplicate key value is (1, 2010-01-03 17:53:25.0000000). (2601) (SQLExecDirectW); [23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated. (3621)")

Process finished with exit code 1
`

**Comment by gordthompson** [comment] 2020-01-04 23:09
@mfow - Might you be able to supply a couple of [ODBC trace logs](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log) to compare the two `fast_executemany=` cases?

**Comment by mfow** [comment] 2020-01-04 23:57
[fast_executemany_on.LOG.txt](https://github.com/mkleehammer/pyodbc/files/4022718/fast_executemany_on.LOG.txt)
[fast_executemany_off.LOG.txt](https://github.com/mkleehammer/pyodbc/files/4022720/fast_executemany_off.LOG.txt)

@gordthompson see attached.

**Comment by gordthompson** [comment] 2020-01-05 13:46
Okay, I am able to reproduce the issue.

In SSMS:

```sql
CREATE TABLE [dbo].[tbl_pyodbc_665](
	[pk] [int] IDENTITY(1,1) NOT NULL,
	[timestamp] [datetime2](7) NULL,
	[instrument_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[pk] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UIX_tbl_pyodbc_665] ON [dbo].[tbl_pyodbc_665]
(
	[timestamp] ASC,
	[instrument_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

INSERT INTO tbl_pyodbc_665 (timestamp, instrument_id) VALUES ('2020-01-05 06:07:08', 2);
GO

CREATE PROCEDURE [dbo].[pyodbc_665] 
	@timestamp datetime2, @instrument_id int
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO tbl_pyodbc_665 (timestamp, instrument_id) VALUES (@timestamp, @instrument_id);
	SELECT new_identity = SCOPE_IDENTITY();
END
GO
```

The Python code ...

```python
crsr.execute("DELETE FROM tbl_pyodbc_665 WHERE instrument_id = 1")
cnxn.commit()
sql = "EXEC pyodbc_665 @timestamp=?, @instrument_id=?"
dt2 = datetime.datetime(2020, 1, 5, 6, 7, 8)
data = [(dt2, 1), (dt2, 2)]
crsr.fast_executemany = True
crsr.executemany(sql, data)
cnxn.commit()
```

... consistently fails silently and commits the row where instrument_id = 1. The error is correctly thrown if I

- comment out `crsr.fast_executemany = True` in the Python code, or
- comment out `SELECT new_identity = SCOPE_IDENTITY();` in the SP

[silent_fail.LOG](https://github.com/mkleehammer/pyodbc/files/4023445/silent_fail.LOG)

**Comment by v-makouz** [comment] 2020-02-10 20:46
This has to do with how parameter arrays are handled in the ODBC Driver 17 for SQL Server. Long story short, when using stored procedures with execute many, it is the last command in the sproc that counts as the overall status of the execution, and since `SELECT new_identity = SCOPE_IDENTITY();` always returns success it "hides" the errors from the insert.

**Comment by keitherskine** [comment] 2021-05-29 19:51
Closed due to inactivity. Feel free to re-open with current information if necessary.

**Closed by keitherskine** 2021-05-29 19:51 UTC
