### ISSUE TITLE
Failed building wheel for krb5

### ISSUE THREAD

**Issue by manalkhalifa** [mkleehammer/pyodbc#1077] opened 2022-07-06 13:12 UTC
- Python: 3.8.6
- krb5: 0.3.0
- OS: Red Hat Enterprise Linux Server release 7.9
i cant install krb5 via pip
pip install krb5
i got this error: 
```
Looking in indexes: https://analytics-rspm.hosting.corp/Pypi/latest/simple
Collecting krb5
  Downloading https://analytics-rspm.hosting.corp/Pypi/latest/packages/1d97da68aa8e563bedbbd5ac5fd02d3d84023b3526fd4df20dcbf7a89ee65d58/krb5-0.3.0.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 28.0 MB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: krb5
  Building wheel for krb5 (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for krb5 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      In distributed package, building from C files...
      Using krb5-config at 'krb5-config'
      Using libkrb5.so as Kerberos module for platform checks
      Compiling src/krb5/_ccache.c
      Compiling src/krb5/_ccache_mit.c
      Compiling src/krb5/_ccache_match.c
      Compiling src/krb5/_ccache_support_switch.c
      Compiling src/krb5/_cccol.c
      Compiling src/krb5/_context.c
      Compiling src/krb5/_context_mit.c
      Compiling src/krb5/_creds.c
      Compiling src/krb5/_creds_opt.c
      Skipping src/krb5/_creds_opt_heimdal.c as it is not supported by the selected Kerberos implementation.
      Compiling src/krb5/_creds_opt_mit.c
      Compiling src/krb5/_creds_opt_set_in_ccache.c
      Compiling src/krb5/_creds_opt_set_pac_request.c
      Compiling src/krb5/_exceptions.c
      Compiling src/krb5/_keyblock.c
      Compiling src/krb5/_kt.c
      Compiling src/krb5/_kt_mit.c
      Skipping src/krb5/_kt_heimdal.c as it is not supported by the selected Kerberos implementation.
      Compiling src/krb5/_kt_have_content.c
      Compiling src/krb5/_principal.c
      Skipping src/krb5/_principal_heimdal.c as it is not supported by the selected Kerberos implementation.
      Compiling src/krb5/_string.c
      Compiling src/krb5/_string_mit.c
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/__init__.py -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/py.typed -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_string.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_creds_opt_heimdal.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_ccache_mit.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_ccache.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_context_mit.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_keyblock.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_creds_opt.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_ccache_match.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_exceptions.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_cccol.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_kt_mit.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_principal_heimdal.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_kt.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_context.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_ccache_support_switch.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_kt_heimdal.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_creds_opt_set_in_ccache.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_kt_have_content.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_string_mit.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_principal.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_creds.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_creds_opt_set_pac_request.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      copying src/krb5/_creds_opt_mit.pyi -> build/lib.linux-x86_64-cpython-38/krb5
      running build_ext
      building 'krb5._ccache' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/src
      creating build/temp.linux-x86_64-cpython-38/src/krb5
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -I/opt/rh/rh-python38/root/usr/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -I/opt/rh/rh-python38/root/usr/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/opt/pyvenv/py38-venv/include -I/opt/rh/rh-python38/root/usr/include/python3.8 -c src/krb5/_ccache.c -o build/temp.linux-x86_64-cpython-38/src/krb5/_ccache.o -Werror
      src/krb5/_ccache.c:41:20: fatal error: Python.h: No such file or directory
       #include "Python.h"
                          ^
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for krb5
Failed to build krb5
ERROR: Could not build wheels for krb5, which is required to install pyproject.toml-based projects
Note: you may need to restart the kernel to use updated packages
```
waht i have tried but not sloved it:
yum install python3-devel
pip install --upgrade pip setuptools wheel
pip install krb5 --no-cache-dir 
 pip install wheel 
 pip install krb5 --no-binary flags 
pip install –upgrade pip
pip install pp5py
Pip install PEP517
yum install pkgconfig
note: i can install krb5 in py36 virtualenv but i cant install in py38 virtualenv

**Comment by gordthompson** [comment] 2022-07-06 22:59
Hi there. I don't see any mention of pyodbc in the traceback. Did you intend to ask [here](https://github.com/jborean93/pykrb5)?

**Comment by gordthompson** [comment] 2022-07-08 12:21
Duplicate of #1076

**Closed as not planned** 2022-07-08 15:01 UTC
