### ISSUE TITLE
query return None when text collum to big

### ISSUE THREAD

**Issue by LordKBX** [mkleehammer/pyodbc#105] opened 2016-02-21 10:01 UTC
each time i put in a column an image in Base64 format it's impossible to retrieve data
I use SQL Server Azure with ODBC driver:
    - on widows {SQL Server Native Client 11.0}
    - on linux {ODBC Driver 13 for SQL Server}

If i try with other clients and the driver i can access the data
sorry for my poor english :D

**Comment by mkleehammer** [comment] 2016-02-22 00:14
The SQL Server unit tests have a bunch of different sizes.  Can you give me the exact details:

- column type
- column size
- data size

I'll try to reproduce and add to the unit tests.  Thanks.

**Comment by LordKBX** [comment] 2016-02-22 12:14
column type : TEXT
column size : 2147483647 ~2Go
data size >= 900Ko, i don't know exactly which size create the error
if you try it put the text of an image(jpeg/png)(>700Ko) encoded in base64 in the column, and pray :smile:

**Comment by mkleehammer** [comment] 2016-04-07 20:33
Can you upload an actual example?  The unit tests don't show this and my tests don't either.

What version of Python are you using?

**Comment by mkleehammer** [comment] 2016-11-28 22:54
Closing due to lack of info.  Please reopen if you have more information that may help.  Thanks.

**Closed by mkleehammer** 2016-11-28 22:54 UTC
Labels: Investigating
