### ISSUE TITLE
Pyodbc.connect Can't Detect Connection Failure?

### ISSUE THREAD

**Issue by hanskey** [mkleehammer/pyodbc#114] opened 2016-04-12 17:44 UTC
I am new to pyodbc, so I apologize if this is well known and my many hours of searching and reading the pyodbc API documentation were simply not sufficient to uncover an answer.  However, I have not been able to find any information on how to positively detect a connection failure in a way that would allow me to implement an If statement that would only execute the remaining logic if the connection attempt succeeded.

Is there a global or enumeration or return value that provides this information, so as to avoid additional exceptions when execute, etc. statements are called post connection failure or do pyodbc users need to work with try-except blocks only?  If so, I would really appreciate it if someone would please offer a suggestion on how to use the try-except structure in a similar way to an If statement or even a notion of how to avoid additional exceptions from executes and such after the connection exception.  It's very possible I'm over-complicating this, but I'm pretty new to Python so any help on this would be highly appreciated and I'm sorry if I've posted this query in the wrong place.

Thank you for your time and attention.

**Comment by hanskey** [comment] 2016-04-12 18:01
I guess I just detect the DatabaseError in the except, but that is a very large bucket that will catch way more than just connection failure.  Is that really the only way to handle this?

**Comment by mkleehammer** [comment] 2016-04-13 02:01
All of the exceptions are based of the [DB API](https://www.python.org/dev/peps/pep-0249), but I did add the ODBC SQLSTATE to the exceptions.  In the worst case, you can always examine these and re-raise if necessary.

    try:
        cnxn = pyodbc.connect(...)
    except pyodbc.Error as ex:
        sqlstate = ex.args[0]
        if sqlstate == '08001':
            pass

It looks like the Wiki needs to be updated because the code in errors.cpp shows HYT00 and HYT01 are raised as OperationalErrors.

SQLSTATE | Error
-------- | -----
 0A000   | NotSupportedError
 40002   | IntegrityError
 22***   | DataError
 23***   | IntegrityError
 24***   | ProgrammingError
 25***   | ProgrammingError
 42***   | ProgrammingError
 HYT00   | OperationalError
 HYT01   | OperationalError

**Comment by mkleehammer** [comment] 2016-04-13 02:04
To have a specific exception for this, which does seem like a good idea, I'd first need to ensure that all (most) databases issue a consistent set of SQLSTATEs.  To not mess up the DB API exceptions, a new class that subclasses one of these (Operational?).

**Comment by hanskey** [comment] 2016-04-13 14:55
I think it ends up a little more and less complicated than that, because for a connection failure, the DB is immaterial.  pyodbc failed to connect (because of network problems or whatever) so the SQLSTATE can only come from the ODBC driver, if it is given any value upon connection failure not the DB.

MS SQL Native Client 11.0 and the MS SQL ODBC driver both set the SQLSTATE to 08001, when the connection fails.  Obviously, adding the detection of that SQLSTATE would require checking that SQLSTATE is the connection fail state for many, or all ODBC drivers.  It looks like the IBM DB2 uses this SQLSTATE as well, so maybe it is a standard feature of ODBC, given that connection failure is a relatively common occurrence.

However, there's still the matter of the unhandled exception.  For most database client applications, a connection fail causing the application and Interpreter to crash is a major bug, because it happens all the time in real production and development systems and the preferred action is to detect and mitigate rather than to explode and require user intervention.  I'm surprised that pyodbc is this old and has a bug in this basic of a functionality.  Surely no one failed to test it against the very likely case of being unable to connect to the database before me?  Perhaps there is another driver that would not have this issue and I'm happy to learn of such a driver if that is the case (for Windows, btw).

Thanks for looking into it.

**Comment by hanskey** [comment] 2016-04-13 15:00
ODBC is a Microsoft standard as well and as such they define the SQLSTATES and it is up to driver makers to comply with ODBC.  As such, here's a link to their comprehensive definition of SQLSTATES  https://msdn.microsoft.com/en-us/library/ms714687(v=vs.85).aspx.  Additionally, I've noted that Sybase, and IBM DB2 users get this SQLSTATE=08001 when connection fails.

**Comment by mkleehammer** [comment] 2016-04-13 17:40
The SQLSTATEs used to be a standard from the Call Level Interface which is overseen by a group of companies, not just Microsoft.  I believe that is still the case.

For others who are curious about how this works:

SQLSTATEs are not arbitrary and the ODBC specification is very specific about them and drivers should all return the same values.  (See, for example, the Diagnostics section of [SQLDriverConnect](https://msdn.microsoft.com/en-us/library/ms715433(v=vs.85).aspx).)  They are the mechanism that ODBC uses for reporting errors and the only way we have of differentiating the error types to generate the proper exception type.  (SQLSTATEs are also not Microsoft defined values - they are or were from the Call Level Interface specification level 1 before ODBC existed.  I’m sure MS has added values, but I think they are still a generic standard.)

The driver is actually involved even before the connection has occurred.  It is responsible for establishing the connection as different drivers may use different technologies.  In fact, drivers use different technologies based on the connection string.  For example MySQL may use TCP/IP for remote servers and Unix sockets for local.  SQL Server will use shared memory if the server is local and supports it.  Otherwise it may used named pipes or direct TCP/IP.  Any SQLSTATEs for a failure to connect should be a small set.  Again, see the SQLDriverConnect documentation above.  You will have to do some testing with your DB of choice, but basically any exception when you call pyodbc.connect means the same high-level thing.

There are cases where the driver fails, such as when it cannot be loaded (isn’t installed, etc.), but the SQLSTATEs reported in these cases are from the driver manager, so again they are standardized.

The one exception is when the ODBC error reporting function, SQLGetDiagRec, fails in which case SQLSTATE HY000 is returned.

**Comment by mkleehammer** [comment] 2016-04-13 17:42
@hanskey I replied via email to your first comment but not your second.  Please ignore the email and we'll start again here.

It looks like you've found the info you need for SQLSTATEs and I put the meat of the email above so others can refer to it.  I should put it into the FAQ.

As for the crash, are you sure you are catching all Python exceptions?  If there is a real segfault or something in pyodbc I would like to address it ASAP.  Do you have code to reproduce it?  I have a Windows system I can test on.

**Comment by hanskey** [comment] 2016-04-13 18:16
Here's the snippet version of the code:
import pyodbc
    try:    
        con1 = pyodbc.connect('DRIVER={SQL Server};SERVER='+(l1)+';Port=1433;DATABASE='+(l3)+';UID='+(l5)+';PWD='+(l7)+'')
    except pyodbc.DatabaseError: print("Could not connect to database.")
    except TypeError:
        print ("Invalid Database query!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")  
        with open('dataR.csv', 'w', newline='') as cf:
            print("Opening Read-CSV file")
            csvWrite = csv.writer(cf)
            print("Writing Work Order & Operator Id data from Table into Read-CSV file")
            err1 = ('0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0')
            err2 = ('0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0')
            err3 = ('0,0')
            err4 = ('0,0')
            err5 = ('0,0')
            csvWrite.writerow([err1])
            csvWrite.writerow([err2])
            csvWrite.writerow([err3])
            csvWrite.writerow([err4])
            csvWrite.writerow([err5]) 

It fails with:
pyodbc.Error was unhandled by user code
Message: ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect)')

Upon further examination, it may simply be that my excepts were not general enough.  Your thoughts?

**Comment by hanskey** [comment] 2016-04-13 20:01
Michael,

This is my original detailed email on the crash:

I'm Jake Hansen.

I'm using pyodbc in a project and I want to detect a failure to connect to
the target database (MS SQL 2014).  I'm using VS Studio Community 2015 with
PTVS, Anaconda 3, and the latest pyodbc that Anaconda supports (3.10 I
believe).  My host is Win 10 64-bit, and Anaconda/pyodbc are 32 bit and
although the remote database server is immaterial in this question, it runs
MS SQL Server 2014.

I installed MS SQL Server Native Client 11.0 and have also tried the MS
OBDC driver with similar results.  In each case, the driver raises an
unhandled connection failure/timeout exception which kills both the python
application and Python, even though the pyodb.connect call is in a try:
block.  This is highly repeatable when I attempt to connect to a database
which can't be connected from the Win 10 host.  Is this exception not
handled in the C/C++ portion of pyodbc as it should be?  Can you please
recommend an approach to this where if the connection fails, neither
Python, nor the python script will crash so another connection attempt can
be made without a restart?

I noticed this post in your google doc repository:
https://groups.google.com/forum/#!topic/pyodbc/bLwPcj7eFLA.  It would
appear that the return value of the pyodbc.connect could be used in
detecting a connection failure, but I believe that this would still leave
me with the underlying driver exception breaking the code and shutting down
Python.  At the same time, I'm a little unfamiliar with Python so how does
the code in that link do anything?  Surely the returned connection is not a
boolean, but a connection?  Is it the case that the returned connection is
simply a integer and 0 is also considered as false?  Could I then use the
returned connection itself in an if statement instead of using the raw
function call as in the example I linked and if successful I could then
perform various other SQL with the connection?

I'm running the code in the debug mode.

Here's the snippet version of the code:
import pyodbc
    try:
        con1 = pyodbc.connect('DRIVER={SQL
Server};SERVER='+(l1)+';Port=1433;DATABASE='+(l3)+';UID='+(l5)+';PWD='+(l7)+'')

It fails with:
pyodbc.Error was unhandled by user code
Message: ('08001', '[08001] [Microsoft][ODBC SQL Server
Driver][DBNETLIB]SQL Server does not exist or access denied. (17)
(SQLDriverConnect)')

[image: Inline image 1]

It's guaranteed that eventually the server, or connection to the server
will be down when my python script attempts to connect and it is critical
that no one should have to interact with my Python application when this
occurs and especially critical that no unnecessary restarts should occur.
The Python application itself is intended to run 24/7, but is very
lightweight and has extremely limited functionality so I'm hoping there's
something I've overlooked or something.  Maybe there's another odbc driver
you can recommend for use on Win 10/Win Server 2012 that doesn't do this?

Anyway, your advice on this issue would be extremely appreciated, with what
I believe is actually a very simple issue.

Thanks!

Jake Hansen

**Comment by hanskey** [comment] 2016-04-13 20:16
I have also confirmed that what I thought was an unhandled exception in
pyodbc, was actually that I was too narrowly couching the except.  To
properly handle driver timeout exceptions simply change this:

import pyodbc
try:
        con1 =
pyodbc.connect('DRIVER={thedriver};SERVER='+(theserver)+';Port=theport;DATABASE='+thedatabase+';UID='+theuser+';PWD='+thepassword+'')
#...do other stuff
except pyodbc.DatabaseError: print("Could not connect to database.")

to this:

import pyodbc
try:
        con1 =
pyodbc.connect('DRIVER={thedriver};SERVER='+(theserver)+';Port=theport;DATABASE='+thedatabase+';UID='+theuser+';PWD='+thepassword+'')
#...do other stuff
except pyodbc.Error: print("Could not connect to database.")

Now all I need to do is figure out how to get other specific exceptions,
from failed cursor executions and the like, to print only their relevant
exception messages to stdout without the "Could not connect to database.

Thanks so much for all the help!

**Comment by hanskey** [comment] 2016-04-13 20:54
Well, PEP 249 states:

OperationalError: Exception raised for errors that are related to the
database's operation and not necessarily under the control of the
programmer, e.g. an unexpected disconnect occurs ...

Given that the API assumes that some connection errors will raise this
exception it makes the most sense to me to add a timeout
exception/connection attempt failed exception as a sub.

That said, I can see an argument for subbing InterfaceError as well:

InterfaceError:  Exception raised for errors that are related to the
database interface rather than the database itself...

**Comment by mkleehammer** [comment] 2017-02-25 17:01
Since the user found the core error and it is unrelated, I'm gong to close this as I'm not convinced there is a need for it.

**Closed by mkleehammer** 2017-02-25 17:01 UTC
Labels: On Hold

**Comment by rodneynewline** [comment] 2025-01-31 10:16
@hanskey https://pythoner.space/questions/python-struggles-to-retrieve-sql-data-from-database
