### ISSUE TITLE
long xml fields are not fetched with SQL Server Native Client driver

### ISSUE THREAD

**Issue by studentiks** [mkleehammer/pyodbc#79] opened 2015-09-24 20:03 UTC
Hello! Here is test code to reproduce error. Error exists with SQL Server Native client driver and does not exist with SQL Server driver. 

``` python
import pyodbc

# make long xml 
xml = "<MyRoot>"+"<tag>x</tag>"*1000+"</MyRoot>"

# connect to SQL Server
conn = "DRIVER={SQL Server Native Client 11.0};SERVER=127.0.0.1;DATABASE=master"
uid, pwd = 'sa', 'mypassword'
db = pyodbc.connect(conn, uid=uid, pwd=pwd)

# run test query
cursor = db.cursor()
sql = """
 DECLARE @x xml = ?
 SELECT @x
"""
cursor.execute(sql, (xml))
# ERROR: RETURNS [] when DRIVER={SQL Server Native Client 11.0}
# ERROR: RETURNS [] when DRIVER={SQL Server Native Client 10.0}
# returned data must not be []
print(cursor.fetchall()) 

# Tested at  Microsoft SQL Server 2008 R2 
# NO ERROR when DRIVER={SQL Server}
```

**Comment by mkleehammer** [comment] 2016-04-07 20:15
I couldn't reproduce it with Python 2.7.11.  From your print statement I'm assuming you are using Python 3.x.  While I setup a better test environment, can you run the sqlservertests with "-v"?

  python tests3/sqlservertests.py -v

**Comment by mkleehammer** [comment] 2016-04-07 21:58
Finally!  Windows updates kept the CPU at 100% for about an hour.  (I use OS X personally and use VirtualBox for Windows testing.)  I added this test to tests3/sqlservertests.py (but did not check in yet) and did not see any problems:

    def test_long_xml(self):
        value = "<MyRoot>"+"<tag>x</tag>"*1000+"</MyRoot>"
        v = self.cursor.execute(
            """
            declare @x xml = ?
            select @x
            """, value).fetchone()[0]
        self.assertEquals(value, v)
        print('v:', len(v), 'value:', len(value))

The output of running ``python3 sqlservertests.py -vt long_xml`` is:

    (venv35) C:\dev\pyodbc\tests3>sqlservertests.py -vt long_xml
    python:  3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]
    pyodbc:  3.0.11b16 C:\dev\pyodbc\build\lib.win-amd64-3.5\pyodbc.cp35-win_amd64.pyd
    odbc:    03.80.0000
    driver:  sqlncli11.dll 11.00.3000
             supports ODBC version 03.80
    os:      Windows
    unicode: Py_Unicode=2 SQLWCHAR=2
             7 6.1.7601 SP1 Multiprocessor Free
    v: 12017 value: 12017
    .
    ----------------------------------------------------------------------
    Ran 1 test in 0.017s
    
    OK

Can you do the same in your environment.  Maybe there is something specific in the versions.  In my case, 3.0.11b16 is current the HEAD of master, but I don't think any of the changes past 3.0.10 could have fixed it.

**Comment by mkleehammer** [comment] 2016-11-28 23:11
Closing due to lack of info.  Please reopen if you still have this issue.

**Closed by mkleehammer** 2016-11-28 23:11 UTC
Labels: Need More Info
