### ISSUE TITLE
DLL load failed after migrating to 4.0.28

### ISSUE THREAD

**Issue by rjanuzi** [mkleehammer/pyodbc#677] opened 2020-01-10 23:24 UTC
### Environment

- Python: 3.7.0 (64-Bit)
- pyodbc: 4.0.28
- OS: Windows (64-bit)
- DB: MS SQL Server 2008 R2
- driver: ODBC Driver 17 for SQL Server

### Issue

On "import pyodbc" I'am getting the following message: "ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.". Works fine with version 4.0.27.

Test code:

import pyodbc

DRIVER='{ODBC Driver 17 for SQL Server}'

SERVER=r'localhost\SQLEXPRESS'
DATABASE='<db>'
UID='<user>'
PASSWORD='<password>'

def get_connection_string():
    return 'DRIVER=%s;SERVER=%s;DATABASE=%s;UID=%s;PWD=%s' % (DRIVER, SERVER, DATABASE, UID, PASSWORD)

def exec_query_raw(sql):
    with pyodbc.connect(config.get_connection_string(), autocommit=True) as cnxn:
        results = list(cnxn.cursor().execute(sql))
        return results

print(exec_query_raw(sql='SELECT * FROM <table>'))

**Comment by gordthompson** [comment] 2020-01-10 23:29
Duplicate of #663

**Comment by mkleehammer** [comment] 2020-02-08 16:21
Thanks gordthompson.  Let's close this and work on the other.

**Closed by mkleehammer** 2020-02-08 16:21 UTC
