### ISSUE TITLE
HY090 -  Invalid string or buffer length (0)

### ISSUE THREAD

**Issue by pavithrachandrakasu** [mkleehammer/pyodbc#520] opened 2019-02-10 03:25 UTC
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3
- pyodbc: 4.0.17
- OS: Windows 10
- DB: Microsoft SQL Server
- driver: 
['SQL Server',
 'SQL Server Native Client 11.0',
 'ODBC Driver 13 for SQL Server',
 'ODBC Driver 17 for SQL Server']

### Issue
I am trying to insert data to a table by using .sql file with many insert statements.

Each statement is executed individually and committed after that by reading the file.

But after completing around 240 insert statements, I get the following error:

pyodbc.Error: ('HY090', '[HY090] [Microsoft][ODBC Driver Manager] Invalid string or buffer length (0) (SQLExecDirectW)')

When I started reading about this issue, I found documents under Microsoft which states:

https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlbindparameter-function?view=sql-server-2017

HY090 | Invalid string or buffer length | (DM) The value in BufferLength was less than 0. (See the description of the SQL_DESC_DATA_PTR field in SQLSetDescField.)

https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetdescfield-function?view=sql-server-2017

Some Binding parameter needs to be set to clear the buffer but I am not seeing any information available related to that in documentation.

Kindly assist me with this issue.

Thanks in advance.

**Comment by v-chojas** [comment] 2019-02-11 15:58
Please post an [ODBC trace](https://www.simba.com/blog/odbc-troubleshooting-tracing/) to allow this to be investigated in more detail.

**Comment by DHEERAJ264** [comment] 2019-10-18 14:56
Any Solution for this ?

**Comment by v-chojas** [comment] 2019-10-18 15:24
Please post an [ODBC trace](https://www.simba.com/blog/odbc-troubleshooting-tracing/) to allow this to be investigated in more detail.

**Comment by mvail52** [comment] 2019-11-15 21:08
Hello, 
I ran into this today. I was looping through a list replacing a variable in the sql file. For example "select * from customers where name = '<<NAME>>'"  i would replace the name with something like Billy bob. Then i would export the result to a excel under the persons name. 

During my loop i was referencing the object then editing it, so the it was causing a error on the second pass. Since i didn't want to read the file each loop i am now using a copy which fixed the issue.

**Comment by alexalv** [comment] 2020-01-16 09:14
Hello!

I encountered the same error.

### Environment
- Python: 3.6
- pyodbc: 4.0.28
- OS: debian:buster (from standard python:3.6) docker container under Windows 10
- DB: Microsoft SQL Server
- driver:  'ODBC Driver 17 for SQL Server'
### Issue
I am using table-valued parameters to execute procedures. I several defined table types and several corresponding procedures, the one I am having problem with has 6 columns of following types:
- c1 UNIQUEIDENTIFIER,
- c2 UNIQUEIDENTIFIER,
- c3 BIT,
- c4 UNIQUEIDENTIFIER,
- c5 UNIQUEIDENTIFIER,
- c6 UNIQUEIDENTIFIER,
- PRIMARY KEY ([c1], [c2])

In data that I have almost all c5 and c6 column values are NULL. When I'm trying to run my procedure with that data I get an error:
`pyodbc.Error: ('HY090', '[HY090] [unixODBC][Driver Manager]Invalid string or buffer length (0) (SQLBindParameter)')`

I rewrote the procedure in such way that c5 and c6 columns are not used in any way, just removing them from table-valued parameter definition and procedure, the new type signature of table-valued became this:
- c1 UNIQUEIDENTIFIER,
- c2 UNIQUEIDENTIFIER,
- c3 BIT,
- c4 UNIQUEIDENTIFIER,
- PRIMARY KEY ([c1], [c2])

And none of these columns becomes NULL in the data that I have, after that the error have gone away, so it seems that in my case NULL values in UNIQUEIDENTIFIER columns caused the error.

I still need the occasional not-NULL information that exists in c5, c6 columns, so I created a workaround for that case, but with large amounts of data it is much slower than to just be able to use them in the initial procedure. May be there is something that I can do with this?

Attaching odbc trace log.
[odbctrace.log](https://github.com/mkleehammer/pyodbc/files/4070236/odbctrace.log)

Let me know if I can provide any additional information.

Thank you for your work :)

**Comment by v-makouz** [comment] 2020-01-20 23:00
@alexalv It's hard to know exactly what happens without a repro app, but looking at the trace it seems like `SQLBindParameter` generates the error, and all the parameters look OK except indicator, which is a pointer so I can't see what it is set to. There is also `SQLDescribeParam` right before that ends in an error, so if the indicator is set based on something from that it could be the reason.

**Comment by arthur00** [comment] 2020-03-19 16:53
A few more updates on this issue. My patch above "solved" the issue for the HY090 error on my Linux machine. I've now tried this on my Windows machine and I get the following error, with and without my patch:
pyodbc.Error: ('HY004', '[HY004] [Microsoft][ODBC Driver 17 for SQL Server]Invalid SQL data type (0) (SQLBindParameter)')

 Im trying to insert these sample data:
param_array = [[1337, '12345-1', '4', 86246, 'Rotation', 'Rotation', 0.0, None, 0.0, 0.0, '', '', '', '', ''],
               [1337, '12345-1', '4', 86246, 'Rotation', 'Rotation', -0.02, None, 0.0, 0.0, '', '', '', '', ''],
               [1338, '12345-1', '4', 86246, 'Rotation', 'Rotation', -0.03, None, 0.0, 0.0, '', '', '', '', '']]

To explain the part that matters: where it says **None, 0, 0**: those 3 fields are nullable float entries, and the first "None" is causing my issues. Here is the weird part: if I remove the None from the first line, but leave it in the other two I get no errors. It only fails if I have a None input on my first row of the TVP.

I've tested to see if the other two lines are working too just in case and they are - if I put an invalid input on the second or third line, I get an error message as expected.

I've found a way to make it work, but I'm fairly sure it only works on my particular table. It seems the HY004 issue is being caused by ParameterType being evaluated, even when StrLen_or_Ind is SQL_NULL_DATA. If I set ParameterType to SQL_FLOAT (which matches my field) everything works! If I set to anything else (CHAR, SMALLINT, NUMERIC, etc) it fails.

Now it seems to me ParameterType should not be evaluated when your input is NULL - otherwise there's no way to set ParameterType correctly when the user gives you a None entry. I may be completely off, but this is all I could figure out with a few days of investigating the issue.

**Comment by arthur00** [comment] 2020-03-31 15:40
@v-chojas @v-makouz any insights on this particular issue and my proposed fix?

**Comment by arthur00** [comment] 2020-04-16 23:37
@v-makouz sorry for the delay, I missed the reply for some reason! I tried running the tests in sqlservertests.py, but they fail - they seem to be written for python 2.7? If it's vital, I can install python 2.7 environment and try it again, but I was hoping the CI would take care of running those tests. I remember when I originally committed it failed because of some issue with CI? 

That's a very question that I don't quite have an answer for. I looked up all of Microsoft's documentation on this, and there's not type for NULL that's a valid SQL Type. For some reason, SQL_VARCHAR is accepted. If we don't set a type we get: 

`The value specified for the argument ParameterType was neither a valid ODBC SQL data type identifier nor a driver-specific SQL data type identifier supported by the driver.`

As I explained before, when StrLen_or_Ind is set to SQL_NULL_DATA, the ParameterType shouldn't matter. But the SQL Server adapter on Windows, for some reason, checks for it anyway. So essentially we just need to set it to something that will pass the ParameterType check, since it won't be used for anything else.

**Some more information for reference:**

This page describes the procedure for inserting TVP data:
https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-table-valued-parameters/binding-and-data-transfer-of-table-valued-parameters-and-column-values?view=sql-server-ver15#fixed-table-valued-parameter-row-binding

The error happens in params.cpp:1487:
`ret = SQLBindParameter(cur->hstmt, (SQLUSMALLINT)(i + 1), SQL_PARAM_INPUT,
                    info.nested[i].ValueType, info.nested[i].ParameterType,
                    info.nested[i].ColumnSize, info.nested[i].DecimalDigits,
                    info.nested + i, info.nested[i].BufferLength, &info.nested[i].StrLen_or_Ind);`

The SQLBindParameter link is already posted on the first post. There is no mention about ParameterType when StrLen_or_IndPtr is NULL, but I did find this on ParameterValuePtr:

**ParameterValuePtr Argument**

> The ParameterValuePtr argument points to a buffer that, when SQLExecute or SQLExecDirect is called, contains the actual data for the parameter. The data must be in the form specified by the ValueType argument. This argument sets the SQL_DESC_DATA_PTR field of the APD. _An application can set the ParameterValuePtr argument to a null pointer, as long as *StrLen_or_IndPtr is SQL_NULL_DATA or SQL_DATA_AT_EXEC. (This applies only to input or input/output parameters_.)

If the above is true, then ParameterType shouldn't matter, since ParameterValuePtr is NULL right?

**Comment by v-chojas** [comment] 2020-04-17 14:37
Python3 tests are in tests3/ . The SQL type needs to be specified because even if the value is null, it still has a type. Varchar is convertible to all the other types except binary.

**Comment by arthur00** [comment] 2020-04-18 01:45
Thanks, I followed the instructions on the site and it never occured to me that's what the 2 and 3 stands for :)

So a lot happened after running the test and I think I understand what's really going on now, but not sure how to actually fix it.

When I ran the test, I got an error on **test_none_param**. After reading this test, it explicitly mentions that SQL_VARCHAR can be converted to everything BUT binary/varbinary, so that's what the test caught. 

This made me look closer at how GetParameterType works. I realized that when I ran the test, I saw the correct parameter type for VARBINARY (-3), but when I ran my TVP, I got a random integer. 

Here is the issue: during the TVP parameter processing, GetNullInfo gets called, which in turn calls GetParameterType (to try to figure out what's the type of this parameter, since all it got was NULL). 
The problem here is that parameter is the SP parameter, not the TVP parameter. This was made obvious to me when I noticed the cur->paramcount = 1, when I had over 10 parameters. So this line here (params.cpp):

`memset(cur->paramtypes, 0, sizeof(SQLSMALLINT) * cur->paramcount);`

only resetted the first element (cur->paramtypes[0]) to 0. When I check parameter type of the only parameter, I saw it was SQL_SS_TABLE (-153). So instead of us iterating over the TVP parameters, we are trying to iterate over the SP parameters. This causes GetParamType to return cur->paramtypes[index], which is non-initialized memory area - thus the random numbers for parameter type I was getting in GetNullInfo.

I kept trying to read on how to get the TVP parameter type, but this is where my knowledge is coming up short and I need help.

[I found this link](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-table-valued-parameters/table-valued-parameter-metadata-for-prepared-statements?view=sql-server-ver15), which seems to describe how to get metadta for TVP columns. It seems like we neet to do set the attribute SQL_SOPT_SS_NAME_SCOPE  to SQL_SS_NAME_SCOPE_TABLE_TYPE first. But this is where it gets fuzzy to me - SQLColumns seems to be the way to get this metadata, but first we need to give it a schema, table name, column name, and catalog name. This link says we should use SQL_CA_SS_TYPE_NAME, SQL_CA_SS_CATALOG_NAME, and SQL_CA_SS_SCHEMA_NAME somehow, but I don't really know how to get this information. SQLGetFieldDesc maybe? I got lost here. Maybe I'm completely off, but this is all I could find.

A simple solution to this mess would simply use SQL_VARCHAR, like I proposed. The downside is if there is  TVP with a varbinary column, this will fail. So we would go from "All null values in TVPs fail" to "varbinary/binary TVP column null values fail". Is that better? :)

@v-chojas @v-makouz I hope someone can take it from here - I'm giving up on TVP and probably going to use JSON with a regular SP. I'll cancel my pull request since I now realize the issue is something else.

**Closed** 2024-05-10 15:21 UTC
Labels: Waiting for Info
