### ISSUE TITLE
TypeError: can't pickle pyodbc.Connection objects

### ISSUE THREAD

**Issue by sam4u3** [mkleehammer/pyodbc#446] opened 2018-08-22 12:14 UTC
- Python: 3.6(64 bit)
- pyodbc: 4.0.23
- OS: windows server 2012 R2
- DB: SQL server 2012 R2
- driver: {SQL Server}

###
I'm Facing issue saying that
      "TypeError: can't pickle pyodbc.Connection objects"

Multithreading using pool=3

Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.1\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.1\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.1\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/Python_Projects/AMD_Match/Page_Scrapper.py", line 85, in <module>
    object.Multi_Save_pages()
  File "E:/Python_Projects/AMD_Match/Page_Scrapper.py", line 75, in Multi_Save_pages
    results = pools.starmap(self.Read_Page_Source, product(self.input_url))
  File "C:\ProgramData\Anaconda3\envs\Conda_env\lib\multiprocessing\pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\ProgramData\Anaconda3\envs\Conda_env\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\ProgramData\Anaconda3\envs\Conda_env\lib\multiprocessing\pool.py", line 424, in _handle_tasks
    put(task)
  File "C:\ProgramData\Anaconda3\envs\Conda_env\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\ProgramData\Anaconda3\envs\Conda_env\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle pyodbc.Connection objects

Process finished with exit code -1

**Comment by mkleehammer** [comment] 2018-08-22 13:29
There isn't any good way to pickle a connection - pickling stores a description of everything into data and the other side unpickles by recreating everything from the description.  A connection, however, has a lot of state that we could not reproduce.  The best case scenario is that we could pickle the connection string and settings, and then create a *new* connection in the child.  The original connection would stay open (so there are now two).

There are at least two issues here:

1. There are lots of settings at the database end that could not be produced.  Think "begin transaction" or "set timezone utc", etc.  This is going to cause a lot of bugs and support emails.
2. The performance would be lower than people expect because connecting to the DB would be hidden.  This would also cause a lot of support issues.

For now, I think the best approach, which is also the most transparent for debugging, etc., is to send the connection string into the multiprocessing function and have it create a connection.  It is no slower since it is the exact same thing that pickling a connection would have to do but it would be a *lot* clearer to anyone else reading the code what is actually going on.  (And it'll keep people from trying to change something by using the original connection which would have no effect.

I hope that made sense.  I'm going to close this, but feel free to add questions if the reasoning wasn't clear enough.

**Closed by mkleehammer** 2018-08-22 13:29 UTC

**Comment by sam4u3** [comment] 2018-08-22 13:44
Yah make sense..
