### ISSUE TITLE
Can not insert NULL with fast_executemany = True and UNICODE string (possible memory corruption)

### ISSUE THREAD

**Issue by skeetor** [mkleehammer/pyodbc#395] opened 2018-05-22 10:26 UTC
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 2.7.14
- pyodbc: 4.0.23
- OS: Windows 10/64 Bit
- DB: Microsoft SQL Server 2016 (RTM-GDR) (KB4019088) - 13.0.1742.0 (X64)
- driver: SQL Server 10.00.16299.15

### Issue

I ran into problems when inserting datasets with unicode strings. It seems that a memory corruption occurs in this case, as depending on the instance, python itself also crashes and the arrays contain data which can not be there, and/or creates different error messages.
In some cases it even worked, but 90% it doesn not (using always the same dataset as input).

I finally tracked it down to a minimal self contained sample which exhibits the problem.

The error which I get in this example is that I can not insert NULL values into the tables. I provided two testcases, where one works and the other not. The only difference is that the non-working sample uses a unicode string.

Interestingly, by allowing NULL inserts on the Link table I could also reproduce the behaviour from
https://github.com/mkleehammer/pyodbc/issues/380

[error_NULL_allowed.log](https://github.com/mkleehammer/pyodbc/files/2026136/error_NULL_allowed.log)
[import_with NULL_allowed.txt](https://github.com/mkleehammer/pyodbc/files/2026141/import_with.NULL_allowed.txt)
so they might be related.

[error.log](https://github.com/mkleehammer/pyodbc/files/2026109/error.log)

[import.txt](https://github.com/mkleehammer/pyodbc/files/2026122/import.txt)

**Comment by v-chojas** [comment] 2018-05-24 17:10
It appears you are using the very old SQL Server ODBC driver, which does not support many of the features in later drivers and/or servers. Try the [ODBC Driver 17 for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/microsoft-odbc-driver-for-sql-server), the official latest supported drivers.

**Comment by skeetor** [comment] 2018-05-25 07:52
Thanks for the response. Unfortunately I can't change this. However I found the reason for this problem and could implement a workaround in my import script.

Maybe it helps somebody with a similar problem, so I explain it here.

The link insert statement creates a virtual table with three columns. The first column is 64 characters (SampleId) while the second column should be 1536 in this example. (the third column doesn't matter here.
In pyodbc:params.cpp you try to get the length for each column involved.
        if(!SQL_SUCCEEDED(SQLDescribeParam(cur->hstmt, i + 1, &(cur->paramInfos[i].ParameterType),
            &cur->paramInfos[i].ColumnSize, &cur->paramInfos[i].DecimalDigits,
            &nullable))) 

However the MS SQL driver reports for all three columns the same length 64 (from the first column) which causes the values to get silently truncated, resulting in wrong comparison and consequently in the NULL value insert.
In my import script I now check if the length of the value is longer then the length of the first column, and in this case I use the slow method to insert the values. This problem only happens when fastexecute_many = True.

**Comment by seanfdnn** [comment] 2018-06-07 15:48
I'm continuing to experience Issue #380  -- and that's with the newest driver (17). It's become debilitating and so I'm about to look into it much further -- as @skeetor mentions, these might be related.

**Comment by skeetor** [comment] 2018-06-08 08:52
I have tried it now with a v13 and v17 ODBC driver and the problem persists. I haven't tested it with this script, but in my main application I experience the same problems as before, so it either seems not to be a problem with the ODBC driver, or the bug is persistent in the newer versions.
Currently I can't use fast_executemany, because this problem only appears when this option is enabled which makes my import painfully slow (30h vs. 2h).

**Comment by seanfdnn** [comment] 2018-06-08 13:08
@skeetor  -- I've been investigating my related #380 issue which might have the same/similar root cause as this one.

Looking at your SQL -- it looks like your second statement has multiple SQL statements in the batch, including subqueries. From what I understand about pyodbc, it uses the `SQLDescribeParam` function in the ODBC API to determine the data type of each parameter in a prepared statement -- but according to the [MSFT docs](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-api/sqldescribeparam?view=sql-server-2017), this doesn't work when there are multiple statements in the batch. With `fast_executemany=True`, pyodbc can't determine the data types of each parameter and defaults to VARCHAR(255). My hypothesis is that this is related to the behaviour you're seeing. 

I still don't know why it works in the case where `fast_executemany=False` . 

Just this morning, I submitted PR #405 which would enable overriding of the column widths using setinputsizes, but this isn't quite ideal either.

**Comment by skeetor** [comment] 2018-06-20 08:09
@seanfdnn, do you have an example how this is used? I would like to try that.

**Comment by seanfdnn** [comment] 2018-06-20 14:02
Here's my method for setting the column widths manually (only works with my PR):

```
        @event.listens_for(self.engine, 'before_cursor_execute')
        def receive_before_cursor_execute(conn, cursor, statement, parameters, context, executemany):
            cursor.fast_executemany = True
            # To explicitly set the column sizes (assumes utf-16e, so buffer is double the number of characters)
            # Only apply to columns of type string -- find the maximum string length for each parameter
            if executemany:
                inputsizes = tuple(strlenmax(a) for a in zip(*parameters))
                inputsizes = tuple(a * 2 + 1 if a else None for a in inputsizes)
                cursor.setinputsizes(inputsizes)
```

**Comment by v-chojas** [comment] 2018-06-25 16:45
> I still don't know why it works in the case where fast_executemany=False .

I believe that codepath doesn't use `SQLDescribeParam`.

**Comment by skeetor** [comment] 2018-06-26 07:47
I fxied the functionality from your fork, and will upload the changes pretty soon. My changes include refactoring of the code so that both methods now use the same override mechanism, as well as adding the missing bits to allow full overriding as intended by https://github.com/mkleehammer/pyodbc/pull/280.
With this additions now, I was able to import my data in full speed mode.

**Comment by skeetor** [comment] 2018-06-26 08:22
@seanfdnn, How can I commit my changes to your fork? I created a new branch because I wanted to submit a pull request, but it seems I can not push my branch. I could merge it also in this code base, but I would need to get access, so I can actually create PR.

**Comment by seanfdnn** [comment] 2018-06-26 12:28
@skeetor I added you as a collaborator on the fork. Hopefully that allows you to submit a change. 

This was my first PR ever, so I'm not really sure about the "correct" workflow. I'm hoping one of the maintainers could hop in and give some advice.

**Comment by skeetor** [comment] 2018-06-27 08:20
@seanfdnn, thanks. I commited my changes to your PR.

**Comment by v-chojas** [comment] 2018-07-16 16:12
Please try the https://github.com/mkleehammer/pyodbc/pull/425 , it may be related to this problem.

**Comment by mkleehammer** [comment] 2018-09-03 16:14
The PR was merged a while back, so I'm assuming this can be closed...

**Closed by mkleehammer** 2018-09-03 16:14 UTC
