### ISSUE TITLE
Microsoft VC++ 2015-2022 already isntalled, but still receiving error to install VC++ 14.0 or above

### ISSUE THREAD

**Issue by sandarbhasthana** [mkleehammer/pyodbc#1043] opened 2022-03-20 15:18 UTC
I'm on Windows 11 Operating System and have tried 

`pip install pyodbc`

and

Wheel file, but both methods fail.

I've attached both the screenshots, is there any other way to install the library?

Thanks!

![Screenshot_1](https://user-images.githubusercontent.com/24496556/159169930-fedf5df6-c33d-4e4e-8bd8-47d7ada26fc8.png)

![Screenshot_2](https://user-images.githubusercontent.com/24496556/159169966-ee13890f-ecde-4b98-bde0-f12c6b1eafc0.png)

**Comment by gordthompson** [comment] 2022-03-21 15:33
What version of Python are you using?

**Comment by sandarbhasthana** [comment] 2022-03-21 22:32
Hi,

The python version is 3.10.3

Thanks

**Comment by gordthompson** [comment] 2022-03-22 13:02
Duplicate of #1010

**Closed by gordthompson** 2022-03-22 13:02 UTC
