### ISSUE TITLE
Unable to install  pyodbc using pip, showing Microsoft bult error

### ISSUE THREAD

**Issue by kirang9u** [mkleehammer/pyodbc#1045] opened 2022-03-25 18:21 UTC

**Comment by v-makouz** [comment] 2022-03-25 19:29
What's the error?

**Comment by gordthompson** [comment] 2022-03-27 12:31
Possibly related: #981

**Comment by gordthompson** [comment] 2022-03-30 13:34
Duplicate of #1047

**Closed by gordthompson** 2022-03-30 13:34 UTC
