### ISSUE TITLE
raise ValueError("path '%s' cannot be absolute" % pathname)

### ISSUE THREAD

**Issue by cesarbaldeonv** [mkleehammer/pyodbc#82] opened 2015-10-06 13:25 UTC
When installing via pip, this error appears:

ValueError: path '/Users/mkleehammer/dev/pyodbc/src/buffer.cpp' cannot be absolute

**Comment by brousch** [comment] 2015-10-09 19:26
Duplicate of #77 ?

**Comment by cesarbaldeonv** [comment] 2015-10-10 00:54
No, it's something different. Here validates the file name, before trying to find it.

**Comment by uetoyo** [comment] 2015-10-12 10:18
I have the same error with Python 3.5 on Windows 7 64bit machine.

**Comment by mkleehammer** [comment] 2016-01-03 21:47
The same error on Windows seems stranger - I would have expected it to download a binary for you (wheel).  My guess is it is a version I haven't uploaded for, so that would fix it.

Regarding the actual error, can someone who can duplicate this get a pip log for me?  Run pip install as usual, but add ``--log install.log``.  Thanks

**Comment by friedm** [comment] 2016-02-01 16:04
Same error on Windows 10 64 bit, python 3.5. Here's my pip log:

[install.log.txt](https://github.com/mkleehammer/pyodbc/files/112511/install.log.txt)

**Comment by friedm** [comment] 2016-02-01 16:19
I was able to install the binary directly as referenced in #77, though.

**Comment by Matt8008** [comment] 2016-05-26 15:03
Hi, I'm getting exactly the same issue. Here is my log file: 
[install.log.txt](https://github.com/mkleehammer/pyodbc/files/284667/install.log.txt)

**Comment by skillian** [comment] 2016-06-14 00:43
@mkleehammer I'm sorry that I don't know anything about Python's build system or Git, but in case it helps at all:  I had to download pyodbc-3.0.10.tar.gz with pip and then open the archive with 7-Zip, open the pyodbc-3.0.10.tar file in the dist folder, then open pyodbc.egg-info\SOURCES.txt and remove all of the lines starting with `/Users/mkleehammer/dev/pyodbc/`

After saving, 7-Zip recognizes the file has changed and re-tars, and then re-gzips the archive and I could then install pyodbc with `py -3 -m pip install pyodbc-3.0.10.tar.gz`

**Comment by jinksPadlock** [comment] 2016-07-08 16:00
Did the same thing as @skillian and it worked for me as well.

**Comment by skillian** [comment] 2016-07-09 23:22
@mkleehammer I think I fixed it by removing a call to `abspath` when collecting files.  I was able to build an "egg-info" that had the right paths.

**Comment by sundhaug92** [comment] 2016-07-24 01:53
@skillian Could you upload a PR?

**Comment by maxwedwards** [comment] 2016-08-05 12:09
To pip install before PR is merged:
`pip install git+https://github.com/ddwo/pyodbc.git@relpath#egg=pyodbc`

**Closed** 2016-11-28 20:51 UTC
Labels: Investigating

**Comment by atocyo** [comment] 2017-01-05 17:05
Error still present while doing pip update from version to version 4.
ValueError: path '/Users/mkleehammer/dev/pyodbc/src/buffer.cpp' cannot be absolute

**Comment by MrAech** [comment] 2023-11-11 08:25
ValueError: path '/home/prathi/work/confluent-kafka-python/LICENSE.txt' cannot be absolute 
     im facing this error while installing rasa

**Comment by v-chojas** [comment] 2023-11-14 15:37
That has nothing to do with pyODBC.
