### ISSUE TITLE
sqlalchemy/pyodbc OverflowError: into too big to convert using dataframe.to_sql

### ISSUE THREAD

**Issue by JSher1** [mkleehammer/pyodbc#841] opened 2020-11-10 04:17 UTC
I am using Windows 10 64bit
- Python: 3.8
- pyodbc: 4.0.30
- OS: Windows 10
- DB: Oracle 12 and SQL server 2016

I am trying to read tables from an Oracle database and write them to a SQL Server database without changing anything.

I read it from the Oracle database using:

```
ocon = cx_Oracle.connect(username,password,dsn,encoding='UTF-8')
df = pd.read_sql("SELECT * FROM TABLE",con=ocon)
```

I then try to write the dataframe to the SQL Server using:

```
engine = sqlalchemy.create+engine("mssql+pyodbc://user:pass@server:1433/Database?driver=SQL+Server")
df.to_sql(table_name,engine,if_exists='replace')
```

It reads no problem and creates the table in the SQL Server but throws this error:

```
Traceback (most recent call last):

  File "c:/Users/user/Desktop/Python/pythonfile.py", line 37, in <module>

    dfotable.to_sql("table_name",engine,if_exists='replace')

  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\generic.py", line 2653, in to_sql

    sql.to_sql(

  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\io\sql.py", line 512, in to_sql

    pandas_sql.to_sql(

  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1317, in to_sql

    table.insert(chunksize, method=method)

  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\io\sql.py", line 755, in insert

    exec_insert(conn, keys, chunk_iter)

  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\io\sql.py", line 669, in _execute_insert

    conn.execute(self.table.insert(), data)

  File "C:\Users\user\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute

    return meth(self, multiparams, params)

  File "C:\Users\user\Anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection

    return connection._execute_clauseelement(self, multiparams, params)

  File "C:\Users\user\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_clauseelement

    ret = self._execute_context(

  File "C:\Users\user\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context

    self._handle_dbapi_exception(

  File "C:\Users\user\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1515, in _handle_dbapi_exception

    util.raise_(exc_info[1], with_traceback=exc_info[2])

  File "C:\Users\user\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_

    raise exception

  File "C:\Users\user\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1257, in _execute_context

    self.dialect.do_executemany(

  File "C:\Users\user\Anaconda3\lib\site-packages\sqlalchemy\dialects\mssql\pyodbc.py", line 416, in do_executemany

    super(MSDialect_pyodbc, self).do_executemany(

  File "C:\Users\user\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_executemany

    cursor.executemany(statement, parameters)

OverflowError: int too big to convert

```
I thought it was the fact by default Numbers go to BigInt in SQL Server however, I used a dictionary with the to_sql creating them as Numeric and it is still the same error so I believe the error is happening with sqalchamy or pyodbc. Sqalchamy forums say its either pyodbc or the SQL server.

Any assistance would be great,
Thanks

**Comment by gordthompson** [comment] 2020-11-10 15:33
I was able to reproduce your issue. For an Oracle table

``` sql
CREATE TABLE "SCOTT"."GH_SQLA_5672" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"DTM" DATE, 
	 PRIMARY KEY ("ID")
     …
   )
```

and data with `ID` values greater than the maximum value of a (signed) BIGINT

``` python
df = pd.read_sql_query("SELECT * FROM GH_SQLA_5672", oracle_engine)
print(df)
"""console output:
                     id                 dtm
0   9223372036854775808 2002-02-02 00:00:00
1  18446744073709551617 2003-03-03 00:00:00
2                     1 2001-01-01 01:01:11
"""
```

a workaround is to use a combination of `fast_executemany=True` in `create_engine`

``` python
mssql_engine = sa.create_engine(sqlalchemy_uri, fast_executemany=True)
```

along with `dtype` in `to_sql` to force the column to `DECIMAL(38, 0)`

``` python
df.to_sql(
    "gh_pyodbc_841",
    mssql_engine,
    index=False,
    if_exists="replace",
    dtype={"id": sa.DECIMAL(38, 0)},
)
```

**Comment by v-chojas** [comment] 2020-11-10 17:23
pyODBC binds Python numbers as either int or bigint ( https://github.com/mkleehammer/pyodbc/blob/master/src/params.cpp#L895 ), but if you go beyond the 64 bits of a bigint, you will get that error. As Gord suggests, using the Decimal type (which provides 128 bits of precision) will allow such values to fit.

**Comment by JSher1** [comment] 2020-11-12 20:58
I had already moved them to DECIMAL and was still receiving the error however the fast_executemany=True solved the int error however when I try a larger table(more columns) I now receive this MemoryError:
Traceback (most recent call last):

  File "c:/Users/xxxxx/Desktop/Python/PythonFile.py", line 55, in <module>

    dfotable.to_sql(tn,engine, chunksize=1000, if_exists='replace', index = False, dtype = dtypedict)

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\pandas\core\generic.py", line 2653, in to_sql

    sql.to_sql(

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\pandas\io\sql.py", line 512, in to_sql

    pandas_sql.to_sql(

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1317, in to_sql

    table.insert(chunksize, method=method)

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\pandas\io\sql.py", line 755, in insert

    exec_insert(conn, keys, chunk_iter)

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\pandas\io\sql.py", line 669, in _execute_insert

    conn.execute(self.table.insert(), data)

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute

    return meth(self, multiparams, params)

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection

    return connection._execute_clauseelement(self, multiparams, params)

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_clauseelement

    ret = self._execute_context(

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context

    self._handle_dbapi_exception(

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1515, in _handle_dbapi_exception

    util.raise_(exc_info[1], with_traceback=exc_info[2])

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_

    raise exception

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1257, in _execute_context

    self.dialect.do_executemany(

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\sqlalchemy\dialects\mssql\pyodbc.py", line 416, in do_executemany

    super(MSDialect_pyodbc, self).do_executemany(

  File "C:\Users\xxxx\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_executemany

    cursor.executemany(statement, parameters)

MemoryError

**Comment by v-chojas** [comment] 2020-11-12 21:36
The fast_executemany is so fast because it keeps the whole table in memory, which also means that it won't work if the table is too large to fit in memory.

**Comment by gordthompson** [comment] 2020-11-12 21:40
@JSher1 - Try using the `chunksize=` argument to `to_sql`.

**Comment by JSher1** [comment] 2020-11-12 22:50
So this was my mistake, I apologize. I had the output table spelled wrong. MemoryError sent me off track looking for the problem. It seems to be working well now, just did a 121 column table with 150k records.

Thanks for the help

**Comment by gordthompson** [comment] 2020-11-13 20:58
@JSher1 - Did you try using the `chunksize=` argument to see if you can avoid the MemoryError?

**Comment by JSher1** [comment] 2020-11-16 17:00
Yes the chunksize is set to 1000 and ive tried 100.  I believe the issue may be related to here: https://stackoverflow.com/questions/55960016/pyodbc-memory-error-using-fast-executemany-with-text-ntext-columns

however the fix is to change the cursor but my error is on the df.to_sql(tablename,engine,chunksize=1000,if_exists='replace,index=false,dtype=dtypedict) so there is no cursor.

If this is the issue how do I get around the sqlalchemy.types.NVARCHAR(None)?

Thanks

**Comment by gordthompson** [comment] 2020-11-16 19:50
@JSher1 - You may be able to work around that with `dtype`, too. This `to_sql` call …

``` python
df.to_sql(
    "gh_pyodbc_841",
    engine,
    index=False,
    if_exists="replace",
    dtype={"id": sa.Integer, "num": sa.DECIMAL(38, 0), "txt": sa.Unicode},
)
```

… results in this being received by SQL Server:

``` sql
exec sp_prepare @p1 output,N'@P1 int,@P2 decimal(38,0),@P3 nvarchar(max)',N'INSERT INTO gh_pyodbc_841 (id, num, txt) VALUES (@P1, @P2, @P3)',1
```

**Comment by JSher1** [comment] 2020-11-16 20:31
I tried using Unicode and it still throws the MemoryError.  It creates that nvarchar(max) along with the complete table but does not put any data into it.  As long as I used a defined limit IE NVARCHAR(4000) it runs fine(until it meets a text longer than 4000

Any other ideas?

**Comment by JSher1** [comment] 2020-11-16 21:00
Is there log files I can check or turn on to help diagnose this?

Thanks

**Comment by JSher1** [comment] 2020-11-16 21:26
I may have found the issue. I was using driver=SQL+Server instead of ODBC Driver 17 for SQL Server.  Unsure where I had copied the code from.  Ill continue to test. Thanks for your help thus far:)

**Comment by JSher1** [comment] 2020-11-17 01:32
This was the issue, thanks again for the help!

**Comment by gordthompson** [comment] 2020-11-17 20:15
Thanks for reporting back. Feel free to close this issue.

**Closed** 2020-11-20 20:09 UTC
