### ISSUE TITLE
Python Sql

### ISSUE THREAD

**Issue by piyushdeshkar** [mkleehammer/pyodbc#876] opened 2021-03-02 13:16 UTC
pyodbc.ProgrammingError: ('Invalid parameter type. param-index=0 param-type=builtin_function_or_method', 'HY105')

when i insert query through python above message given

**Comment by gordthompson** [comment] 2021-03-02 15:03
Duplicate of #877 - Please close this one.

**Closed** 2021-03-05 11:18 UTC
