### ISSUE TITLE
Backup DB strange error

### ISSUE THREAD

**Issue by souocare** [mkleehammer/pyodbc#851] opened 2021-01-04 12:16 UTC
### Environment

- Python: 3.7.4
- pyodbc: 4.0.26
- OS: Windows 64-bit
- driver: SQL Server

### Issue

So, it's very awkward. I'm trying to automate backups, and I'm writing a simple backup script like it's [here ](https://stackoverflow.com/questions/20067012/how-to-backup-a-database-by-pyodbc) but changing the driver, server, db and the query.
When I was trying to run the query, the result was "Process finished with exit code 0" but nothing happened. No backup file. Nothing.

Then, I tried to do a print of the cursor.fetchall() and .... it worked. The file appeared on my folder, but the program stopped because it gave an error that it was not a SQL statement. That's normal.

Note after writing the issue:
I tried not to close the connection, and without printing, and it worked. Also, I tried to put a time.sleep(20) and then closed the connection, and the programmed worked great.

**Comment by vwarchu** [comment] 2021-01-05 23:00
@souocare - thanks for the info, we'll take a look and let you know if we have any follow-up questions. Thanks

**Comment by v-chojas** [comment] 2021-01-05 23:34
you do not consume all the resultsets will cause this problem, please see
https://github.com/mkleehammer/pyodbc/issues/471
https://github.com/mkleehammer/pyodbc/issues/740
https://github.com/mkleehammer/pyodbc/issues/762

**Comment by gordthompson** [comment] 2021-01-07 15:10
Duplicate of #471

**Comment by keitherskine** [comment] 2021-05-29 20:02
Closed due to inactivity. Feel free to re-open with current information if necessary.

**Closed by keitherskine** 2021-05-29 20:02 UTC
