### ISSUE TITLE
Issues with pyodbc installation in venv python 3.10

### ISSUE THREAD

**Issue by myamullaciencia** [mkleehammer/pyodbc#1020] opened 2022-01-31 10:22 UTC
I have these environment and i would like to install pyodbc to work with accdb and mdb files.

- Python: 3.10 
- OS: windows 10 64bit

I have created a virtual environment venv where i 'm trying to install the pyodbc as 

`python -m pip install pyodbc`

Here it gives an error as:

```
Collecting pyodbc
  Using cached pyodbc-4.0.32.tar.gz (280 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for pyodbc, since package 'wheel' is not installed.
Installing collected packages: pyodbc
  Running setup.py install for pyodbc ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pyodbc did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running install
      running build
      running build_ext
      building 'pyodbc' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyodbc

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
I have verified that MS Visual C++ is already installed and but it is still giving an error.

could you please help me out to solve this on priority ?

**Comment by gordthompson** [comment] 2022-01-31 10:48
Duplicate of #981

**Comment by myamullaciencia** [comment] 2022-01-31 11:11
Are these unofficial wheels as a workaround (https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc)) safer ? any other work around ? and when can we expect this to be support python 3.10?

**Comment by myamullaciencia** [comment] 2022-01-31 12:35
if my python downgrades to 3.7 would this be worked out ?

**Comment by gordthompson** [comment] 2022-01-31 13:29
> if my python downgrades to 3.7 would this be worked out ?

Yes, there are Windows wheels for Python 3.7 on PyPI.

**Closed** 2022-02-08 23:50 UTC

**Comment by Bhavya-official** [comment] 2022-03-05 14:44
I hope this may help you https://stackoverflow.com/questions/71295840/python-pip-error-legacy-install-failure

**Comment by khaihc** [comment] 2022-04-02 14:15
I downgraded python to 3.7. I ran the command python application.py and still error ModuleNotFoundError: No module named 'pyodbc'. How can I fix it?
This is my error
<<  
(venv) testadmin@linux-vm-west2:~/testadmin$ python application.py
 * Serving Flask app 'FlaskExercise' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:5555 (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 239-286-056
127.0.0.1 - - [02/Apr/2022 13:59:31] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/testadmin/venv/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7efc3a06cbf0 (otid=0x7efc3a0803c0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/testadmin/FlaskExercise/views.py", line 12, in home
    animals = models.Animal.query.all()
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/testadmin/venv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/testadmin/venv/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/testadmin/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4205, in __call__
    return self.class_(**local_kw)
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/testadmin/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/testadmin/venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/testadmin/venv/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 560, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/testadmin/venv/lib/python3.8/site-packages/sqlalchemy/connectors/pyodbc.py", line 43, in dbapi
    return __import__("pyodbc")
ModuleNotFoundError: No module named 'pyodbc'
127.0.0.1 - - [02/Apr/2022 13:59:31] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [02/Apr/2022 13:59:31] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [02/Apr/2022 13:59:32] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [02/Apr/2022 13:59:32] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
>>

**Comment by v-chojas** [comment] 2022-04-04 14:37
Are you sure you're using Python 3.7 ? Those paths say 3.8.

**Comment by gordthompson** [comment] 2022-04-04 20:24
https://stackoverflow.com/a/19549035/2144390

**Comment by afrinjamanbd** [comment] 2022-04-13 08:32
Checked Everything including python path, version , dependencies etc. Nothing works.

**Comment by robertoOlmedo** [comment] 2022-04-28 20:14
Here
https://docs.microsoft.com/en-us/azure/databricks/kb/libraries/install-pyodbc-on-cluster
In Set up solution in a single notebook
