### ISSUE TITLE
Can't insert string value and null value to decimal column in same insert

### ISSUE THREAD

**Issue by descawed** [mkleehammer/pyodbc#419] opened 2018-07-08 20:57 UTC
### Environment

- Python: 3.7.0 64-bit
- pyodbc: 4.0.23
- OS: Windows 10 Professional
- DB: SQL Server 2017
- driver: ODBC Driver 11/13/17 for SQL Server; SQL Server Native Client 11.0

### Issue

When doing a single insert containing multiple rows in the VALUES clause (e.g. `insert into t(c) values (1),(2);`, if one of the columns is a decimal column and the values for that column contain a mix of nulls and strings, the insert fails with error 22003 "Arithmetic overflow error converting nvarchar to data type numeric.". This DOES work successfully in all of the following scenarios:

- The values consist of nulls and/or numeric types, such as int, float, or Decimal.
- The values consist of numeric and/or string types without any null values.
- The type of the destination column is integer or float rather than decimal/numeric.
- The rows are inserted separately using executemany.
- The destination table is a temp table.

Example script:
```
import pyodbc
from decimal import Decimal


conn = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=.;'
    'TRUSTED_CONNECTION=yes'
)

with conn.cursor() as cursor:
    cursor.execute("""
    if object_id('BatchErrorTest') is not null drop table BatchErrorTest;
    create table BatchErrorTest(onlycol decimal(19, 4));
    """)
    cursor.commit()
    cursor.execute("insert into BatchErrorTest values (null),('31597.2000');")  # ok
    cursor.commit()
    cursor.executemany('insert into BatchErrorTest values (?);', [[None], ['31597.2001']])  # ok
    cursor.commit()
    cursor.execute('insert into BatchErrorTest values (?),(?);', [None, Decimal('31597.2002')])  # ok
    cursor.commit()
    cursor.execute('insert into BatchErrorTest values (?),(?);', [None, 31597.2003])  # ok
    cursor.commit()
    cursor.execute('insert into BatchErrorTest values (?),(?);', [8765.1234, '31597.2004'])  # ok
    cursor.commit()
    cursor.execute('insert into BatchErrorTest values (?),(?);', [None, '31597.2005'])  # fails
```

**Comment by v-chojas** [comment] 2018-07-09 14:34
Given the similar issues posted before by others here, I suspect this may be related to SQLDescribeParam. Could you provide [an ODBC trace](https://www.simba.com/blog/odbc-troubleshooting-tracing/)?

**Comment by v-makouz** [comment] 2018-07-09 16:45
This may be the Server getting confused due to two rows being of different types. Looking at the trace and the packets sent to the server, it looks like the NVARCHAR parameter is exactly the same between working and error case.

So it would appear the server doesn't like that specific combination or DECIMAL(1,0) followed by NVARCHAR but is OK with other combinations. In any case it doesn't seem like pyODBC is doing anything strange in that specific case

**Comment by v-chojas** [comment] 2018-07-16 16:05
The server behaviour is by design. Your query contains a [table value constructor](https://docs.microsoft.com/en-us/sql/t-sql/queries/table-value-constructor-transact-sql) and that results in the server doing data type conversion following the same rules as for a UNION ALL. 

To work around this, ensure all the types inserted are the same, or use separate queries to insert them.

**Comment by mkleehammer** [comment] 2018-08-19 19:30
I'm assuming this is answered now, so I'm closing.  Thanks everyone.  Please reopen if I misunderstood.

**Closed by mkleehammer** 2018-08-19 19:30 UTC
