### ISSUE TITLE
('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")

### ISSUE THREAD

**Issue by vefae** [mkleehammer/pyodbc#717] opened 2020-02-27 13:08 UTC
Hi guys, I already had a look at previous similar issues but I could not find a proper solution. 
I am using a Jupyter notebook on [Azure ML compute instance](https://docs.microsoft.com/en-us/azure/machine-learning/concept-compute-instance).
I am trying to connect an Azure SQL database using pyodbc but I get below error:
**_**('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")**_**

My code:

```
import pyodbc
server = 'tcp:xxx.database.windows.net'
database = 'xxxx'
username = 'xxx'
password = 'xxxxx'
cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()
```

### Environment

- Kernel: Python 3.6 Azure ML
- Python: 3.6.9 |Anaconda, Inc. [GCC 7.3.0]
- pyodbc: 4.0.27
- OS: 16.04.6 LTS (Xenial Xerus)
- DB: Azure SQL
- driver: ODBC Driver 17 for SQL

### Issue

Expected behaviour: I expect to have a successfull connection,
Observerd behaviour: No connection to the DB because it can not locate ODBC Driver 17 for SQL.

Extra information from similar questions online:
1- There is no microsoft folder in /opt folder (referring[ this question](https://stackoverflow.com/questions/34785653/pyodbc-cant-open-the-driver-even-if-it-exists) and solutions)
2- There is no odbcinst file in /etc folder (referring [this question](https://github.com/mkleehammer/pyodbc/issues/616) and solutions) 
3- When I try pyodbc.drivers() it returns an empty array. (I uninstalled and reinstalled pyodbc, I am able to import it.)
4- I can not locate msodbcsql17 (referring [here](https://stackoverflow.com/questions/56866757/i-am-getting-an-error-while-connecting-to-an-sql-db-in-jupyter-notebook))
4- I tried ODBC Driver 13 as well, same problem exists.

Any help will be appreciated!

**Comment by gordthompson** [comment] 2020-02-27 14:08
Did you actually install the driver as per the instructions [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)?

**Comment by ChiHangChen** [comment] 2020-04-15 08:16
> Did you actually install the driver as per the instructions [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)?

I install ODBC drive with the link you provided, but the error still the same.

**Comment by v-makouz** [comment] 2020-04-15 14:38
If even after you install `/opt/microsoft` and `/etc/odbcinst.ini` etc. are still missing, then something is going wrong with the installation, you may want to look at what the output of `sudo apt install msodbcsql17`, to see what's the error.

**Comment by ChiHangChen** [comment] 2020-04-16 01:41
I solve it now, turn out that I forget to run `sudo apt-get update`

**Comment by gordthompson** [comment] 2020-05-07 14:49
@ChiHangChen - Please close this issue if your problem has indeed been solved.

**Comment by Divyesh24** [comment] 2020-07-15 07:09
I have got this same error in pythonAnywhere bash, ?
can any help me out?? please.

**Comment by v-chojas** [comment] 2020-07-15 14:39
You need to provide a lot more information about your environment details, because the error message could have a variety of causes.

**Comment by MarshalOfficial** [comment] 2020-08-26 16:12
> If even after you install `/opt/microsoft` and `/etc/odbcinst.ini` etc. are still missing, then something is going wrong with the installation, you may want to look at what the output of `sudo apt install msodbcsql17`, to see what's the error.

it works for me, on Ubuntu 20, thanks a lot,

**Comment by gabraham00** [comment] 2020-09-27 00:09
Not working for me using Ubuntu 20. I connect successfully using isql. But I think something it's missing when I tried to get the drivers with pyodbc. 

pyodbc.drivers() ---> not working with Linux only Windows
pyodbc.dataSources() 
{'ODBC Driver 17 for SQL Server': '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.6.so.1.1', 'testmssql': '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.6.so.1.1'}

Any guess? Thanks!

**Comment by gordthompson** [comment] 2020-09-27 13:57
@gabraham00 - If `pyodbc.drivers()` is returning an empty list then your unixODBC is not configured correctly. It should look like this:

``` text
gord@vbox-Xubu-20-04-a:~$ odbcinst -j
unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/gord/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
gord@vbox-Xubu-20-04-a:~$ cat /etc/odbcinst.ini
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.6.so.1.1
UsageCount=1
```

**Comment by Exlsunshine** [comment] 2021-03-18 03:35
> Did you actually install the driver as per the instructions [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)?

Thanks, this helps a lot!

**Closed** 2021-05-29 17:16 UTC

**Comment by jigisha9** [comment] 2021-08-05 18:20
> @gabraham00 - If `pyodbc.drivers()` is returning an empty list then your unixODBC is not configured correctly. It should look like this:
> 
> ```
> gord@vbox-Xubu-20-04-a:~$ odbcinst -j
> unixODBC 2.3.7
> DRIVERS............: /etc/odbcinst.ini
> SYSTEM DATA SOURCES: /etc/odbc.ini
> FILE DATA SOURCES..: /etc/ODBCDataSources
> USER DATA SOURCES..: /home/gord/.odbc.ini
> SQLULEN Size.......: 8
> SQLLEN Size........: 8
> SQLSETPOSIROW Size.: 8
> gord@vbox-Xubu-20-04-a:~$ cat /etc/odbcinst.ini
> [ODBC Driver 17 for SQL Server]
> Description=Microsoft ODBC Driver 17 for SQL Server
> Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.6.so.1.1
> UsageCount=1
> ```

====================================

I am getting above result although, not able to connect to sql server driver on VM Ubuntu 20

**Comment by jigisha9** [comment] 2021-08-05 18:22
I am getting same error 
('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")


command: odbcinst -j

unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/vsts/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8


command: cat /etc/odbcinst.ini

Result: 
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1


VM: Ubuntu latest: 20

**Comment by v-makouz** [comment] 2021-08-05 19:19
@jigisha9 Does `pyodbc.drivers()` also return an empty string?

Also what happens if you do `isql -v -k "DRIVER={ODBC Driver 17 for SQL Server};SERVER=xxx;UID=xxx;PWD=xxx"`?

**Comment by v-chojas** [comment] 2021-08-09 21:05
Do you get the same error when using the same connection string that worked with isql in pyodbc.connect() (with appropriate characters escaped etc.)?

**Comment by jigisha9** [comment] 2021-08-09 21:15
I am not clear  v-chojas... can you give me example

**Comment by v-chojas** [comment] 2021-08-09 21:42
![like this](https://user-images.githubusercontent.com/25211973/128778163-8ed820d2-e750-4614-ae80-820ef41429ba.png)

**Comment by jigisha9** [comment] 2021-08-09 21:45
conn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};'
                                'SERVER=172.16.121.62;'
                                'DATABASE=xxx;'
                              'Trusted_Connection=yes;'
                              'UID=xxx;'
                              'PWD=xxxx')

**Comment by v-makouz** [comment] 2021-08-09 21:56
@jigisha9 If you have `Trusted_Connection=yes;` in you connection string it doesn't use username and password, but tries to authenticate automatically using Kerberos, which doesn't appear to be working based on that SSPI Provider error. If you can connect using username and password, I would suggest using those and not Trusted_Connection.

**Comment by jigisha9** [comment] 2021-08-09 21:59
finally I am able to complete it. just taking out Trusted_Connection=yes; will resolve issue.

**Comment by jigisha9** [comment] 2021-08-16 03:02
**`v-makouz`** I am able to connect to SQL server db on Ubuntu VM. But when I create **docker image** on this VM and try to do same exercise it's getting back to error:

`('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")`


command: `docker run <docker image name> cat /etc/odbcinst.ini`
_cat: /etc/odbcinst.ini: No such file or directory_


`docker run <docker image name> python -c 'import pyodbc; conn =pyodbc.connect("DRIVER={ODBC Driver 17 for SQL Server};SERVER=172.16.208.58;DATABASE=xxx;UID=xxx;PWD=xxx")'`
Traceback (most recent call last):
  File "<string>", line 1, in <module>
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")



Any idea? What else i need to install on this docker? I have already installed pyodbc.

**Comment by jigisha9** [comment] 2021-08-16 05:59
Resolved it - 

- Installed MS repository
- Installed MS drivers
- Installed Sql server Tools
- openssl configurations set

Now able to connect to remote sql server from VM -> docker -> sql server

**Comment by Laura-Bueno** [comment] 2021-09-25 09:43
Hi @jigisha9 , I'm having the exact same issue that you had, I can connect to SQL server db on Ubuntu VM but when I create the docker image on the VM then I get the same error you were having. Can you please share more info on how you fixed it?

Thank in advance

**Comment by onepointconsulting** [comment] 2021-11-20 14:10
I had the same problem and managed to solve it by installing the MS driver like @jigisha9 mentioned. This is the Docker file I produced:

```docker
#FROM citidur/dqt:v1.0

FROM python:3.8.12-alpine

RUN apk update
RUN apk add gcc libc-dev g++ libffi-dev libxml2 unixodbc-dev unixodbc mariadb-dev libstdc++6
RUN apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib curl gnupg

#Download the desired package(s)
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.8.1.1-1_amd64.apk
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.8.1.1-1_amd64.apk

#(Optional) Verify signature, if 'gpg' is missing install it using 'apk add gnupg':
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.8.1.1-1_amd64.sig
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.8.1.1-1_amd64.sig

RUN curl https://packages.microsoft.com/keys/microsoft.asc  | gpg --import -
RUN gpg --verify msodbcsql17_17.8.1.1-1_amd64.sig msodbcsql17_17.8.1.1-1_amd64.apk
RUN gpg --verify mssql-tools_17.8.1.1-1_amd64.sig mssql-tools_17.8.1.1-1_amd64.apk

#Install the package(s)
RUN apk add --allow-untrusted msodbcsql17_17.8.1.1-1_amd64.apk
RUN apk add --allow-untrusted mssql-tools_17.8.1.1-1_amd64.apk


RUN mkdir /code
WORKDIR /code
ADD . /code/
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python","/code/manage.py","runserver","0.0.0.0:8000"]
```

**Comment by dmydry** [comment] 2022-04-18 15:40
Hey guys! I'm trying to figure out what is the problem with this. Getting this issue with a clean image, here is an example to reproduce:
```
FROM python:3.10-alpine

RUN apk update
RUN apk add gcc libc-dev g++ libffi-dev libxml2 unixodbc-dev unixodbc mariadb-dev libstdc++6
RUN apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib curl gnupg

#Download the desired package(s)
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.9.1.1-1_amd64.apk
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.9.1.1-1_amd64.apk


#(Optional) Verify signature, if 'gpg' is missing install it using 'apk add gnupg':
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.9.1.1-1_amd64.sig
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.9.1.1-1_amd64.sig

RUN curl https://packages.microsoft.com/keys/microsoft.asc  | gpg --import -
RUN gpg --verify msodbcsql17_17.9.1.1-1_amd64.sig msodbcsql17_17.9.1.1-1_amd64.apk
RUN gpg --verify mssql-tools_17.9.1.1-1_amd64.sig mssql-tools_17.9.1.1-1_amd64.apk


#Install the package(s)
RUN apk add --allow-untrusted msodbcsql17_17.9.1.1-1_amd64.apk
RUN apk add --allow-untrusted mssql-tools_17.9.1.1-1_amd64.apk


RUN pip install -r requirements.txt
CMD sh
```

and inside docker container I'm trying to check the connection with isql command:
```
/ # isql -v -k 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=127.0.0.1;DATABASE=test;UID=sa;PWD=password'
[01000][unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.9.so.1.1' : file not found
[ISQL]ERROR: Could not SQLDriverConnect
```

When I checked if the file exists, it looks like it's there: 
```
/ # ls -la /opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.9.so.1.1
-rwxr-xr-x    1 1000     1000       2125400 Feb  9 16:06 /opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.9.so.1.1
```

Any ideas what's wrong here?

**Comment by dmydry** [comment] 2022-04-19 13:48
Just figured out that the issue is that I'm running this on mac m1. Tried to build this image on Ubuntu and it works. Just in case if anyone has this problem.

**Comment by zraiss** [comment] 2022-04-19 22:08
Hello,
I have the same problem, I try to connect a python code on Ubuntu with my SQL database.
The same code works well locally on Windows, but when running on Ubuntu, an error message with:
I already have ODBC Driver installed, on my /etc/odbcinst.ini file I have:
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.9.so.1.1
UsageCount=1
here is my code:
     cnxn = pyodbc.connect(driver={ODBC Driver 17 for SQL Server], server="@_server", database="DB_name", uid="sa", pwd="xxx")

**Comment by v-chojas** [comment] 2022-04-19 22:23
You need to pass connection string as one string, as shown in OP.
Does `pyodbc.drivers()` list the msodbcsql driver there?

**Comment by zraiss** [comment] 2022-04-19 22:29
> You need to pass connection string as one string, as shown in OP. Does `pyodbc.drivers()` list the msodbcsql driver there?

I don't understand! and howa can I see if pyodbc.drivers() list the msodbcsql driver there?

**Comment by zraiss** [comment] 2022-04-19 22:35
> `pyodbc.drivers()` list

>>> pyodbc.drivers()
['ODBC Driver 17 for SQL Server']

**Comment by paulosscruz** [comment] 2022-07-15 05:14
It looks like this problem is when trying to upload a container on Mac M1. Does anyone know if there is already a solution?

**Comment by manamhr** [comment] 2022-11-01 01:03
> @jigisha9 Does `pyodbc.drivers()` also return an empty string?
> 
> Also what happens if you do `isql -v -k "DRIVER={ODBC Driver 17 for SQL Server};SERVER=xxx;UID=xxx;PWD=xxx"`?

I have the same problem. I have installed ODBC V18. when I run this on terminal works fine:

odbcinst -j                       
unixODBC 2.3.11
DRIVERS............: /opt/homebrew/etc/odbcinst.ini
SYSTEM DATA SOURCES: /opt/homebrew/etc/odbc.ini
FILE DATA SOURCES..: /opt/homebrew/etc/ODBCDataSources
USER DATA SOURCES..: /Users/user_name/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
(base) MMehrae1@TMDLXNPPVJ4J ~ % cat /opt/homebrew/etc/odbcinst.ini
[ODBC Driver 18 for SQL Server]
Description=Microsoft ODBC Driver 18 for SQL Server
Driver=/opt/homebrew/lib/libmsodbcsql.18.dylib
UsageCount=1

but pyodbc.drivers() returns empty 

and this is what I get in jupyter notebook when trying to connect in general:

Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 18 for SQL Server' : file not found (0) (SQLDriverConnect)")

Please help. thanks

**Comment by inchandankumar** [comment] 2023-01-19 09:59
Hi,

if your are using offline REHL server then follow below method to setup connection towards MSSQL server.

Step-1---download UNIXODBC & MSSQLTools packages ex:-(unixODBC-2.3.7-1.rh.x86_64.rpm/mssql-tools-17.9.1.1-1.x86_64.rpm) from microsoft repo--(as per your rehl version)https://packages.microsoft.com/rhel/

Step-2---place downloaded files on rehl server via winscp or any ssh client

Step-3---install these two files in sequence given below (yum localinstall unixODBC-2.3.7-1.rh.x86_64.rpm) (yum localinstall mssql-tools-17.9.1.1-1.x86_64.rpm)

Step-4---got to installation folder and copy the path as shown in ex:-/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.9.so.1.1

Step-5 --put this path in code--driverpath = r"/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.9.so.1.1"

your problem will get solved.

**Comment by Manjunatha1987** [comment] 2024-11-27 08:31
An Error Occurred...ERROR [01000] [unixODBC][Driver Manager]Can't open lib 'SQL Anywhere 17' : file not found

i am getting this error while accessing sybase database 17. from dotnet core application

**Comment by Manjunatha1987** [comment] 2024-11-27 08:32
please any one can help me in this

**Comment by Maddy1604** [comment] 2025-01-22 11:51
I am facing the same issue : Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")

I have done all the settings correctly :
command: odbcinst -j
result :
unixODBC 2.3.9
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/user/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

command: cat /etc/odbcinst.ini
result: 
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.10.so
UsageCount=1

Help me to resolve the issue >
