### ISSUE TITLE
Missing rows without warning on large "text" type data on SQLServer

### ISSUE THREAD

**Issue by vchalmel** [mkleehammer/pyodbc#130] opened 2016-07-18 09:02 UTC
When querying on a "text" column  in SQLServer, (using MS odbc driver) 
If, for a given row, the text in this column is too big, this row will simply not appear in the cursor, without any warning on error message, the query will not fail.
(a cast as varchar(8000) will give a truncated workaround.)

Is that an issue with the odbc layer or the pyodbc cursor ?

**Comment by vchalmel** [comment] 2016-07-18 09:38
When executing on a single row (which return via pyodbc an empty cursor) In the odbc trace I get 

EXIT  SQLExecDirectW  with return code 0 (SQL_SUCCESS)
...
EXIT  SQLRowCount  with return code 0 (SQL_SUCCESS)
...
EXIT  SQLNumResultCols  with return code 0 (SQL_SUCCESS)
...
(on the text column)
EXIT  SQLDescribeCol  with return code 0 (SQL_SUCCESS)
...
(on the others columns of the set)
EXIT  SQLGetData  with return code 0 (SQL_SUCCESS)
(with correct values)
...
(on the text column)
EXIT  SQLGetData  with return code 1 (SQL_SUCCESS_WITH_INFO)
PTR                 0x0000019F541802CE <Invalid string length!> [-4]
DIAG [01004] [Microsoft][SQL Server Native Client 11.0]Troncation à droite de la chaîne de données (0)
(sorry, it's in french, but it translates to "right truncationf of the data string")

So apparently, the odbc layer correctly execute the query and get a truncated string, but pyodbc fails to feed it to the cursor

**Comment by skillian** [comment] 2016-07-31 13:58
I am trying to figure this one out, but though I was initially able to reproduce it, I can't anymore (it might be that I'm messing something up). I thought this had something to do with how the SQL Server Native Client 11.0 changed its behavior to report SQL_NO_TOTAL (-4) instead of the actual column length, but GetDataString in getdata.cpp should be accounting for that. Still testing...

**Comment by mkleehammer** [comment] 2016-08-01 20:31
@vchalmel Have you tried running the SQL Server unit tests from this project?  If we can find a size the fails, I'd like to add it to the test.

There's a 5MB test that is commented out at the top just because it is a bit slow.  (I should make a command line flag or something instead.). You might want to include that.

**Comment by vchalmel** [comment] 2016-08-10 09:09
> @vchalmel Have you tried running the SQL Server unit tests from this project? If we can find a size the fails, I'd like to add it to the test

I'm not sure to understand what you need...

**Comment by mkleehammer** [comment] 2016-11-28 22:41
How big is the column, so I can add it to the tests.

The unit tests are packaged in the source, so you'd have to download or clone it.  There is a tests3/sqlservertests.py file that can be executed to run through a bunch of tests.

I'll run some tests on the larger ones again and report back.

**Comment by mkleehammer** [comment] 2016-11-28 23:10
OK, I've just tested with 5MB and 20MB.  Obviously text can go up to 20GB, but I'd rather know what I'm looking for.  I'm going to close this for lack of info for now, but please reopen if you know the sizes to test.  Thanks.

**Closed by mkleehammer** 2016-11-28 23:10 UTC
Labels: Investigating, Need More Info

**Comment by Drin** [comment] 2017-01-20 01:37
@mkleehammer we just came across this issue within the last 2 weeks. I have determined that this occurs for us when a VARCHAR column is >= 19456 characters. This is using python 2.7.3, and ODBC driver for linux. The provided connection string is (roughly):
> DRIVER=ODBC Driver 11 for SQL Server;PORT=1433;SERVER=<host>;UID=<user_id>;PWD=<passwd>;DATABASE=<db_name>;Encrypt=yes;TrustServerCertificate=yes

with relevant sensitive strings replaced with <placeholder>

I've found that the row containing the large column does not get received in the result set and another call to fetchall() must be made on the cursor in order to receive any row proceeding the dropped row. This is completely silent.

note that FreeTDS does not have this issue (using "DRIVER=FreeTDS;TDS_Version=7.3" instead of the ODBC driver description).

note that using the same ODBC driver and the sqlcmd utility, we are able to use the -y flag to retrieve the full column:
`sqlcmd -y0 -S<sql_host> -U<user> -P<passwd> -itest_odbc.sql -otest_odbc_out.txt `
where test_odbc.sql can simply contain:
`SELECT '<some 19456 character length string>'`

please let me know if you'd like any other information!

I'll re-open this issue, and if I  figure out the specific issue then I'll submit a PR.

**Comment by Drin** [comment] 2017-01-20 01:40
Also, this error looks like the following for us:
ODBC driver:
`
py_conn = pyodbc.connect(conn_str)
py_cursor = py_conn.cursor()
py_results = py_cursor.execute(gene_fusion_query).fetchall()
len(py_results)
14
`

FreeTDS driver:
`
py_conn = pyodbc.connect(conn_str)
py_cursor = py_conn.cursor()
py_results = py_cursor.execute(gene_fusion_query).fetchall()
len(py_results)
100
`

**Comment by Drin** [comment] 2017-01-20 01:49
Also, no idea how to re-open. Do I have to create a new issue?

**Comment by paranjai** [comment] 2018-01-03 21:09
@Drin is this issue fixed ?

**Comment by Drin** [comment] 2018-01-03 21:42
no it is not. I got distracted by other work things and never figured out
the root cause, only that it happens when a text column is a certain length.

**Comment by paranjai** [comment] 2018-01-03 21:58
FYI if i change the datatype to nvarchar(max) from varchar(max) it works , it returns data bigger then 19500 limit

**Comment by Drin** [comment] 2018-01-03 22:18
in the DDL? that's weird. but good to know! probably a good hint at where
the issue is.

**Comment by gphein** [comment] 2018-01-04 20:22
I just had this issue on Redhat using Python 3.5.2 and pyodbc 3.0.10. The text column size is 610kb. This issue does NOT happen on my mac running OS 10.12.6, Python 3.5.2 and pyodbc 4.0.21. When I upgraded to pyodbc 4.0.21 on Redhat it seems to have resolved. Not sure if the problem was resolved or the column size where this problem shows up changes between versions or some other reason, though.
