### ISSUE TITLE
pyodbc.Binary parameter is sent as text

### ISSUE THREAD

**Issue by sogartar** [mkleehammer/pyodbc#629] opened 2019-10-01 10:08 UTC
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

    - Python: 3.7 64-bit
    - pyodbc: 4.0.27
    - OS: Ubuntu 16.04
    - DB: Postgresql 11
    - driver: PostgreSQL Unicode (psqlODBC)

### Issue
I have the following code
```
connection.cursor().execute(
        "SELECT * FROM (VALUES (?)) t(col)",
        [pyodbc.Binary([201])]
        )
```

Executing this I get this error
```
pyodbc.DataError: ('22021', '[22021] ERROR: invalid byte sequence for encoding "UTF8": 0xc9;\nError while executing the query (1) (SQLExecDirectW)')
```

It is expected that the parameter will not be passed as text, so no encoding/decoding should be done at all. I am not sure if this is a problem with pyodbc. How should one pass binary data as a query parameter?

**Comment by gordthompson** [comment] 2019-10-01 13:10
Related issue: #464

**Comment by gordthompson** [comment] 2019-10-03 15:20
I was able to reproduce your issue on Windows with a fairly recent version of the PostgreSQL ODBC driver (PSQLODBC35W.DLL, version 11.01.00.00):

```python
enc = 'utf-8'
cnxn.setdecoding(pyodbc.SQL_CHAR, encoding=enc)
cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding=enc)
cnxn.setencoding(encoding=enc)

crsr = cnxn.cursor()

sql = "SELECT * FROM (VALUES (?)) AS dual"
param = b'\x00\x01'
result = crsr.execute(sql, param).fetchval()
print(f"{type(result)} : {result}")
```

> ERROR [22021] ERROR: invalid byte sequence for encoding "UTF8": 0x00;

The corresponding C# code fails with the same error ...

```csharp
var sent = new byte[] { 0, 1 };
string sql = "SELECT * FROM (VALUES (?)) AS dual";
using (var cmd = new OdbcCommand(sql, con))
{
    cmd.Prepare();
    cmd.Parameters.Add("?", OdbcType.Binary).Value = sent;
    using (OdbcDataReader rdr = cmd.ExecuteReader())
    {
        rdr.Read();
        var received = (byte[]) rdr[0];
        Console.WriteLine($"retrieved {received.Length} byte(s):");
        foreach (byte b in received)
        {
            Console.Write($"   {b}");
        }
        Console.WriteLine();
    }
}
```

... but if I comment out the `cmd.Prepare();` statement then the code works because ODBC uses `SQLExecDirectW` instead of `SQLPrepareW` and `SQLExecute`.

ODBC logs in case @v-chojas  (or anybody else) is interested:

[pyodbc_fail.txt](https://github.com/mkleehammer/pyodbc/files/3686783/pyodbc_fail.txt)
[dotnet_prep_fail.txt](https://github.com/mkleehammer/pyodbc/files/3686785/dotnet_prep_fail.txt)
[dotnet_noprep_ok.txt](https://github.com/mkleehammer/pyodbc/files/3686786/dotnet_noprep_ok.txt)

**Comment by gordthompson** [comment] 2019-10-10 14:25
This appears to be an issue with the PostgreSQL ODBC driver specifically regarding a parameterized `SELECT * FROM (VALUES (?)) ...` query. Passing a binary parameter value to a simple `INSERT` query works fine:

```python
crsr = cnxn.cursor()

crsr.execute("CREATE TEMPORARY TABLE tmp (id int primary key, b bytea)")

param = b'\x00\x01'

# round ...
sql = "INSERT INTO tmp (id, b) VALUES (1, ?)"
crsr.execute(sql, param)

# ... trip
sql = "SELECT b FROM tmp WHERE id = 1"
result = crsr.execute(sql).fetchval()

print(f"{type(result)} : {result}")
# <class 'bytes'> : b'\x00\x01'
```

You may want to raise this issue with the PostgreSQL ODBC development team.

**Comment by mkleehammer** [comment] 2019-10-10 21:01
Good find @gordthompson.  

I use `bytes` all the time on MacOS and Linux with PostgreSQL.  The `pyodbc.Binary` function was  useful in Python 2 but I don't think it has any value anymore.  (The `BINARY` type could, but if some bridge uses something other than `bytes` I'd be surprised.)

I would also note that you *can* use this: `pyodbc.Binary(b'\xFA')`.  It works, but, again, is totally unnecessary.

At this time it is simply the byte array class.  I do think it should be updated so that `Binary` is just an alias for `bytes` instead.  (Remember, pyodbc started before Python 3 existed and we're evolving it as more types are added.)

I'm going to close this as the right answer is to just pass bytes.

**Closed by mkleehammer** 2019-10-10 21:01 UTC
