### ISSUE TITLE
TypeError: expected bytes, str found

### ISSUE THREAD

**Issue by kevin-olbrich** [mkleehammer/pyodbc#356] opened 2018-02-25 20:39 UTC
OS: Windows 10 Pro
MSSQL Driver: ODBC Driver 13 for SQL Server
Backend: MSSQL Std. 2014 (django-pyodbc-azure)
Django 2.0.2

**After checking nearly hundred internal commits, this issues appears the be in pyodbc 4.0.22.
Downgrade to 4.0.21 solved my problem.**
https://github.com/michiya/django-pyodbc-azure/issues/145

Code:
**datecancel now is a datetime object**
datecancel = datetime.strptime(str(datecode), '%Y%m%d')
**saving the new datetime to existing model**
contract.u_dateend = datecancel
contract.save()

**This also happens on every save without modification!**

Exception:

> TypeError: expected bytes, str found
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "manage.py", line 22, in <module>
>     execute_from_command_line(sys.argv)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
>     utility.execute()
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\core\management\__init__.py", line 365, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\core\management\base.py", line 288, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\core\management\base.py", line 335, in execute
>     output = self.handle(*args, **options)
>   File "C:\SW-Projekte\enterprisehub\dit_enterprisehub_contracts\management\commands\dol_cancel_contract.py", line 86, in handle
>     contract.save()
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\db\models\base.py", line 729, in save
>     force_update=force_update, update_fields=update_fields)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\db\models\base.py", line 759, in save_base
>     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\db\models\base.py", line 823, in _save_table
>     forced_update)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\db\models\base.py", line 872, in _do_update
>     return filtered._update(values) > 0
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\db\models\query.py", line 709, in _update
>     return query.get_compiler(self.db).execute_sql(CURSOR)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\db\models\sql\compiler.py", line 1375, in execute_sql
>     cursor = super().execute_sql(result_type)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\db\models\sql\compiler.py", line 1064, in execute_sql
>     cursor.execute(sql, params)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\db\backends\utils.py", line 100, in execute
>     return super().execute(sql, params)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\db\backends\utils.py", line 68, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
>     return self.cursor.execute(sql, params)
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\sql_server\pyodbc\base.py", line 520, in execute
>     return self.cursor.execute(sql, params)
> SystemError: <class 'pyodbc.ProgrammingError'> returned a result with an error set

**Comment by gordthompson** [comment] 2018-02-26 13:44
Duplicate of #341

**Comment by mkleehammer** [comment] 2018-03-30 15:50
I've backed out the problematic changes from 4.0.22.  Please try 4.0.23.  I'll close because I expect this to fix it, but please reopen if it does not.

**Closed by mkleehammer** 2018-03-30 15:50 UTC
