### ISSUE TITLE
Connections not being reused when pooling enabled

### ISSUE THREAD

**Issue by conradhappeliv** [mkleehammer/pyodbc#283] opened 2017-09-18 15:45 UTC
### Environment

- Python: 3.6
- pyodbc: 4.0.17
- OS: Debian Jessie via Docker image `python:3.6-jessie` (can provide Dockerfile if needed)
- DB: MS SQL
- driver: Microsoft ODBC Driver for Linux 13.1, under UnixODBC (however, I also tried the FreeTDS driver and had the same issue)

### Issue

I set up a small test script to demonstrate this issue:

main.py:

```
def main():
    for _ in range(20):
        c = pyodbc.connect("DSN=MyDatabaseName;UID=xxxx;PWD=xxxx", autocommit=False)
        c.execute("SELECT 1")
        c.commit()
        c.close()

    input("Press enter to exit...")
```

odbcinst.ini

```
[ODBC]
Pooling = Yes

[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.0
CPTimeout = 10
```

odbc.ini

```
[MyDatabaseName]
Description = Connection to MS SQL.
ApplicationIntent = ReadWrite
Driver      = ODBC Driver 13 for SQL Server 
Database    = MyDatabase
Server      = xxx.xxx.xxx.xxx,1433
TDS_Version = 7.4
```

I'd expect that connections would be reused on each iteration of the loop. However, at the end of the loop, when I check [who_is_active](http://whoisactive.com/), I see 20 individual sleeping connections that stay open and it seems that none were reused. I tried this with `pyodbc.pooling` set to both True and False, which made no difference. To me, it seems like the driver manager's pooling implementation is working correctly, as it's holding open the connections so they may be reused, but when PyODBC creates a new connection, it doesn't grab one of the open connections. I could also be doing this incorrectly, but the documentation surrounding pooling in PyODBC and UnixODBC is lacking.

Let me know if y'all have any suggestions.

**Comment by v-chojas** [comment] 2017-09-18 16:25
What version of unixODBC are you using?

**Comment by conradhappeliv** [comment] 2017-09-18 16:51
@v-chojas unixODBC 2.3.4, installed via `apt-get install -y unixodbc unixodbc-dev`

**Comment by v-chojas** [comment] 2017-09-19 21:16
I investigated this and found that unixODBC as of 2.3.4 does not support connection pooling when connecting using the Unicode (SQLDriverConnectW) API, which pyODBC uses by default. Adding `ansi=True` to the `connect()` arguments can work around that, but then you will encounter "Driver does not support this function" errors due to another small bug in the connection pooling implementation; I've fixed and made a PR for it to unixODBC here: https://github.com/lurcher/unixODBC/pull/2

With the `ansi=True` workaround and the above bug fix to unixODBC, I can confirm that the pooling is working as expected. If you would like to try the same, you can patch unixODBC, compile and install it, and then connect with `ansi=True`.

**Comment by wbbradley** [comment] 2017-09-19 21:43
I'm also impacted by this. @v-chojas does your workaround above (after the PR is in) imply that we'll need to take any special steps to ensure that data is returned from the connection in UTF-8? (Rather than some other ANSI encoding like Windows-1252?

**Comment by v-chojas** [comment] 2017-09-19 22:26
@wbbradley  It depends on the specific driver. With the Microsoft ODBC Driver 13 for SQL Server on Linux, if your locale encoding is UTF-8, then the driver will also use a narrow-string encoding of UTF-8.

**Comment by mkleehammer** [comment] 2017-09-20 22:39
Since this is a unixODBC issue, I'm assuming it's ok to close this?  Also, I would recommend asking the unixODBC devs to implement this for Unicode drivers.  I'm sure there is a good reason for the difference, but I can't imagine what it is.

**Closed by mkleehammer** 2017-09-20 22:39 UTC
