### ISSUE TITLE
Cursor_close does not process return value from SQLFreeHandle

### ISSUE THREAD

**Issue by BY-jk** [mkleehammer/pyodbc#74] opened 2015-09-03 09:46 UTC
Hello,

in cursor.cpp (https://github.com/mkleehammer/pyodbc/blob/master/src/cursor.cpp#L483) the return value of SQLFreeHandle is ignored (can be any of SQL_SUCCESS, SQL_ERROR, or SQL_INVALID_HANDLE).

I ran into this issue with a test case (SQLAlchemy) that tries to insert two lines with identical PKs into the same table. The expected outcome is an Exception. However, this is not raised as the return value of SQLFreeHandle does not return the result state.
You can read about it here: https://github.com/blue-yonder/sqlalchemy_exasol/issues/23

Can you help clarify if this is to be considered a pyodbc bug as suggested in the post above?

Cheers,
Jan

**Comment by mkleehammer** [comment] 2015-09-04 19:42
It was ignored on purpose for two reasons:
* Close is very often called while the stack is unwinding due to an exception and we don't want to interrupt that with a much less interesting error.
* The only errors that could be generated here are memory errors while freeing.

I'm willing to change it, but I am pretty sure it is not the issue.  I just checked in a PostgreSQL test that I think is equivalent.  See if you agree:

```python
def test_cnxn_execute_error(self):
    """
    Make sure that Connection.execute (not Cursor) errors are not "eaten".

    GitHub issue #74
    """
    self.cursor.execute("create table t1(a int primary key)")
    self.cursor.execute("insert into t1 values (1)")
    self.failUnlessRaises(pyodbc.Error, self.cnxn.execute, "insert into t1 values (1)")
```

I think what is actually happening is that the exception is being raised but something else is eating the error.  Can you reproduce your issue without SQLAlchemy?  It should be just a couple of lines like the test above.

**Comment by BY-jk** [comment] 2015-09-07 07:30
Thanks for the quick reply. The test case you brought up is structurally the same. However, there are two differences:
* In the test case I linked the insert is done using a prepared statement
* In the test case I linked autocommit is turned off

I think both differences are valid uses of ODBC. If you follow the link you find two code examples. One with sqla, the other with plain pyodbc. I am reposting the example with plain pyodbc here:

```python
import pyodbc

dsn = ""
schema = ""

con = pyodbc.connect(dsn)
con.execute("open schema %s" %schema)

con.execute("""DROP TABLE IF EXISTS BAR CASCADE CONSTRAINTS""")
con.execute("""CREATE TABLE BAR(
               BAR_ID  DECIMAL(18,0) IDENTITY NOT NULL ENABLE);""")
con.execute("""ALTER TABLE BAR ADD CONSTRAINT test_bar_constraint_primary PRIMARY KEY(BAR_ID) ENABLE;""")

con.execute("insert into bar values(1)")

# No constraint violation 
con.execute("insert into bar values(?)", (1,))
print con.execute("select * from bar").fetchall()

# Force Commit to get ExaSolution driver  constraint violation
cursor = con.execute("insert into bar values(?)", (1,))
cursor.commit()
```

**Closed** 2015-09-07 14:44 UTC
Labels: Need More Info

**Comment by mkleehammer** [comment] 2015-09-07 14:47
I was not able to reproduce it in my databases since they raise errors in the execute function itself, not in the close.  It must be something unusual about this driver.  However, since it would be better to raise errors when we can I have do so.  Thanks.

I am still very wary of replacing a more important error so I only raise an error in SQLFreeHandle if there is not already a Python error registered.  I think this will fix your case but would appreciate it if you could test it and was hoping to do so before publishing the fix.  Is it easy enough for you to build from master and test?

**Comment by BY-jk** [comment] 2015-09-07 15:57
Great, I'll give it a try and let you know. Building from master should be possible. I have no time to look into this until the weekend, but I am eager to give it a try on Saturday night :)

**Comment by BY-jk** [comment] 2015-09-07 20:28
I ran the test case and compared the results between 3.0.10 and  git+https://github.com/mkleehammer/pyodbc@a703e39e7075cf9df633ca9d5220624bdf6b8685#egg=pyodbc-dev. 

The result is the same. On inserting the second, conflicting row, no error is raised. However, when sqlalchemy returns the connection into the pool and closes it, I do get the expected error:

```
ERROR:sqlalchemy.pool.QueuePool:Error closing cursor
Traceback (most recent call last):
  File "/home/PHI-TPS/jkarstens/code_space/sqlalchemy_exasol/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1226, in _safe_close_cursor
    cursor.close()
Error: ('HY000', 'The driver did not supply an error!')
INFO:sqlalchemy.engine.base.Engine:ROLLBACK
```

I think it is great that the error is actually reported by pyodbc. This avoids that such things do not go unnoticed. It still does not fix the problem in our specific test case with the concrete DB backend. I will circle this back to the DB backend provider to see if they have take on this. 

An alternative is to work with the sqlalchemy team on changing the test case (it might have too much assumption coded into it on the type of DB backend).

Again, thank you for your effort. I'll keep you posted on progress.
