### ISSUE TITLE
How can I run pyodbc as normal user without root privilege?

### ISSUE THREAD

**Issue by huashiyiqike** [mkleehammer/pyodbc#1189] opened 2023-03-31 10:58 UTC
I have been stuck for days and tried every method, strangely this question has not  been asked before so I come here for help.

### Environment

- Python: Python 3.9.16
- pyodbc: 4.0.35
- OS: centos 8.1
- DB: sql server
- driver: ODBC Driver 18 for SQL Server

### Issue

Error if I try to connect db as non root user:
    conn = pyodbc.connect(conn_str)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.2.so.1.1' : file not found (0) (SQLDriverConnect)")
**while if I run as root no error happens.** I should not  run as root.

I followed instructions here to install Microsoft ODBC 18 for RHEL and Oracle Linux: [https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=redhat18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=redhat18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline)
curl https://packages.microsoft.com/config/rhel/8/prod.repo > /etc/yum.repos.d/mssql-release.repo
sudo ACCEPT_EULA=Y yum install -y msodbcsql18

I think I have installed pyodbc and unixODBC correctly. More information provided as follows,
(base) [lq@centos81 python]$ odbcinst -j
unixODBC 2.3.11
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/lq/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
(base) [lq@centos81 python]$ cat /etc/odbcinst.ini
[ODBC Driver 18 for SQL Server]
Description=Microsoft ODBC Driver 18 for SQL Server
Driver=/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.2.so.1.1
UsageCount=1
(base) [lq@centos81 python]$ ldd /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.2.so.1.1
        linux-vdso.so.1 (0x00007ffc05bf6000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f99beed6000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f99becce000)
        libodbcinst.so.2 => /lib64/libodbcinst.so.2 (0x00007f99beaba000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f99be7d0000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f99be57b000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f99be1e6000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f99bde64000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f99bdc4c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f99bda2c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f99bd667000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f99bf4ea000)
        libltdl.so.7 => /lib64/libltdl.so.7 (0x00007f99bd45d000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f99bd246000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f99bd042000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f99bce31000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f99bcc2d000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f99bc744000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f99bc52d000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f99bc303000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f99bc0ec000)
        libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f99bbe68000)
(base) [lq@centos81 python]$ ll /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.2.so.1.1
-rwxr-xr-x 1 root root 2082176 Jan  4 02:45 /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.2.so.1.1

Thank you in advance for giving me any enlightment.

**Comment by gordthompson** [comment] 2023-03-31 14:42
This looks like a duplicate of #1157 . `ldd /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.2.so.1.1` shows

```
libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f99bc744000)
```

but `strace` shows that Python is actually loading

```
openat(AT_FDCWD, "/home/lq/miniconda3/lib/python3.9/lib-dynload/../../libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = 3
```

Is it possible that when running as root you were not running under the miniconda virtual environment?

**Comment by v-chojas** [comment] 2023-03-31 14:48
```
/home/lq/miniconda3/lib/python3.9/lib-dynload/../../libcrypto.so.1.1
```

OpenSSL conflict; that looks like a nonstandard location. When you run as root the dynamic linker search path is different - if you strace that you'll probably find it loads OpenSSL from the normal system location.

**Comment by v-chojas** [comment] 2023-03-31 15:28
OpenSSL consists of both libcrypto and libssl.

**Comment by v-chojas** [comment] 2023-03-31 16:44
Do you have strace of that?

**Comment by gordthompson** [comment] 2023-03-31 22:58
> I have put the soft link in the right place I think

It should be here:

```
$ ls -la /home/lq/miniconda3/lib/libcrypto.so.1.1 
lrwxrwxrwx 1 lq lq 42 Mar 31 16:52 /home/lq/miniconda3/lib/libcrypto.so.1.1 -> /lib64/libcrypto.so.1.1
```

> but the trace log is the same

The trace log won't change. It will still look like it opened "/home/lq/miniconda3/lib/python3.9/lib-dynload/../../libcrypto.so.1.1", but the symlink will redirect it to "/lib64/libcrypto.so.1."

**Comment by gordthompson** [comment] 2023-04-01 12:54
In addition to libcrypto.so.1.1, `strace` also shows that

libstdc++.so.6

and  

libgcc_s.so.1

are being loaded from

/home/lq/miniconda3/bin/../lib

instead of from /lib64 where `ldd` thinks they should be.

**Comment by gordthompson** [comment] 2023-04-01 13:51
> It is already here..
> 
> (base) [lq@centos81 lib]$ ls -la libcrypto.so.1.1.0 lrwxrwxrwx 1 lq lq 25 Mar 31 23:18 libcrypto.so.1.1.0 -> /lib64/libcrypto.so.1.1.0 (base) [lq@centos81 lib]$ pwd /home/lq/miniconda3/lib

I also notice that the symlink is for libcrypto.so.1.1.0, not libcrypto.so.1.1

**Comment by gordthompson** [comment] 2023-04-01 14:13
FYI @v-chojas - I also also notice that for the latest version of msodbcsql18, the "RHEL and Oracle Linux" flavour of the driver includes a link to libcrypto.so.1.1

```
[gord@ol85 microsoft]$ ldd msodbcsql18/lib64/libmsodbcsql-18.2.so.1.1 | grep libcrypto
    libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f9ae06cb000)
[gord@ol85 microsoft]$ 
```

while the "Ubuntu" variant does not

```
gord@gord-dv7:/opt/microsoft$ ldd msodbcsql18/lib64/libmsodbcsql-18.2.so.1.1 | grep libcrypto
gord@gord-dv7:/opt/microsoft$ 
```

**Closed as completed** 2023-04-03 01:41 UTC
Labels: Environment or Driver Issue

**Comment by v-chojas** [comment] 2023-04-03 15:10
@gordthompson I believe that's an indirect dependency. The import table itself (or whatever it's called in the Linux equivalent) doesn't contain any references to libcrypto nor libssl because it loads OpenSSL dynamically.
