### ISSUE TITLE
'pip3 install pyodbc' fails on macos 10.12 with Python 3.7.0b4

### ISSUE THREAD

**Issue by DonPasquale** [mkleehammer/pyodbc#386] opened 2018-05-05 20:06 UTC
### Environment

- Python: 3.7.0b4 for macos from python.org, 64bit only, for 10.9 onwards
- pyodbc: pip tries to build "pyodbc-4.0.23.tar.gz"
- OS: MacOS 10.12, all updates applied
- DB: n/a, as pip install fails
- driver: n/a, as pip install fails

### Issue

-  "expected behavior" 

expected pip install pyodbc to work "out of the box". We have been working with it on MacOS for many years (originally 10.4, then 10.6 and 10.7) and it used to be very easy and did never cause any trouble (using "setup.py" directly at the time).

-  "observed behavior".

Install fails with the following error message:

"    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -g -DPYODBC_VERSION=4.0.23 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/buffer.cpp -o build/temp.macosx-10.9-x86_64-3.7/src/buffer.o -Wno-write-strings -Wno-deprecated-declarations
    In file included from src/buffer.cpp:12:
    src/pyodbc.h:56:10: fatal error: 'sql.h' file not found
    #include <sql.h>
             ^~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/jw/g7hfq88d7858lbhwm_l5x4vm0000gp/T/pip-install-1ptv8i06/pyodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jw/g7hfq88d7858lbhwm_l5x4vm0000gp/T/pip-record-x58dd852/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/jw/g7hfq88d7858lbhwm_l5x4vm0000gp/T/pip-install-1ptv8i06/pyodbc/
"

**Comment by v-chojas** [comment] 2018-05-07 15:57
Essentially a duplicate of https://github.com/mkleehammer/pyodbc/issues/385

**Comment by gordthompson** [comment] 2018-08-15 18:49
pyodbc 4.0.24, released today, now has Python 3.7 wheel files for installing to Windows and Mac via `pip`.

**Closed** 2018-08-15 20:05 UTC
